In [146]:
import pandas as pd 
import numpy as np

In [147]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [148]:
df = pd.read_csv('data_flats.csv')

In [149]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
rating              341
property_id           9
dtype: int64

In [150]:
df.drop(['link', 'rating', 'property_id'], axis =1 , inplace=True)

In [151]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te..."
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN

In [152]:
df.isnull().sum()

property_name         0
society               1
price                10
area                 13
areaWithType          9
bedRoom               9
bathroom              9
balcony               9
additionalRoom     1323
address              15
floorNum             11
facing              890
agePossession        10
nearbyLocations     104
description           9
furnishDetails      814
features            423
dtype: int64

In [153]:
df = df.dropna(subset=['price'])

In [154]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.5 Crore           59
1.2 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
60 Lac              29
40 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
2.35 Crore          23
1.85 Crore          23
3 Crore             22
70 Lac              21
55 Lac              20
2.25 Crore          20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
2.6 Crore           15
1.38 Crore          15
2.45 Crore          14
3.4 Crore           14
2.15 Crore          14
1.32 Crore          13
3.25 Crore          13
78 Lac              13
92 Lac              13
82 Lac              13
38 Lac              13
2.7 Crore           13
1.95 Crore          12
1.42 Crore          12
5 Crore             12
42 Lac              12
2.8 Crore           12
88 Lac              11
32 Lac              11
25 Lac              11
1.08 Crore          11
Price on Request    11
28 Lac              10
1.28 Crore          10
87 Lac              10
26 Lac              10
1.78 Crore          10
1.12 Crore          10
2.55 Crore          10
1.68 Crore           9
3.45 Crore           9
36 Lac               9
22 Lac               9
2.05 Crore           9
4 Crore              9
1.72 Crore           9
99 Lac               9
2.85 Crore           9
27 Lac               8
1.76 Crore           8
98 Lac               8
1.18 Crore           8
1.26 Crore           8
1.54 Crore           8
4.25 Crore           8
2.75 Crore           8
3.2 Crore            8
6 Crore              8
48 Lac               8
6.5 Crore            8
20 Lac               8
56 Lac               8
86 Lac               8
1.36 Crore           7
1.27 Crore           7
97 Lac               7
3.7 Crore            7
1.19 Crore           7
3.3 Crore            7
72 Lac               7
2.9 Crore            7
1.29 Crore           7
46 Lac               7
39 Lac               7
1.02 Crore           7
1.99 Crore           7
79 Lac               7
1.59 Crore           6
43 Lac               6
1.49 Crore           6
1.01 Crore           6
2.95 Crore           6
3.9 Crore            6
96 Lac               6
3.65 Crore           6
5.5 Crore            6
1.07 Crore           6
1.98 Crore           6
21 Lac               6
54 Lac               6
1.39 Crore           6
3.35 Crore           6
1.13 Crore           6
71.5 Lac             6
37 Lac               6
4.1 Crore            6
1.34 Crore           6
3.05 Crore           6
1.14 Crore           6
1.16 Crore           6
1.51 Crore           6
1.24 Crore           5
1.33 Crore           5
1.17 Crore           5
2.22 Crore           5
6.75 Crore           5
1.91 Crore           5
1.82 Crore           5
2.78 Crore           5
1.69 Crore           5
1.44 Crore           5
49 Lac               5
3.75 Crore           5
1.92 Crore           5
1.43 Crore           5
66 Lac               5
2.29 Crore           5
1.79 Crore           5
93 Lac               5
1.62 Crore           5
1.83 Crore           5
1.93 Crore           5
4.5 Crore            5
64 Lac               5
2.12 Crore           5
29 Lac               5
24 Lac               5
1.47 Crore           5
68 Lac               5
1.64 Crore           4
2.09 Crore           4
1.37 Crore           4
5.25 Crore           4
3.6 Crore            4
4.3 Crore            4
5.6 Crore            4
1.22 Crore           4
58 Lac               4
4.85 Crore           4
62 Lac               4
1.23 Crore           4
1.77 Crore           4
41.5 Lac             4
1.52 Crore           4
28.5 Lac             4
1.73 Crore           4
33 Lac               4
7 Crore              4
1.31 Crore           4
36.5 Lac             4
1.48 Crore           4
5.9 Crore            4
3.95 Crore           4
6.15 Crore           4
73 Lac               4
1.58 Crore           4
1.71 Crore           4
89 Lac               4
67 Lac               4
31 Lac               4
1.66 Crore           4
74 Lac               4
3.1 Crore            4
2.24 Crore           3
83 Lac               3
72.5 Lac             3
47 Lac               3
2.36 Crore           3
1.21 Crore           3
1.04 Crore           3
4.75 Crore           3
2.03 Crore           3
3.8 Crore            3
64.5 Lac             3
91 Lac               3
5.8 Crore            3
4.8 Crore            3
1.67 Crore           3
2.51 Crore           3
3.49 Crore           3
2.01 Crore           3
2.08 Crore           3
51 Lac               3
52 Lac               3
84 Lac               3
69 Lac               3
1.57 Crore           3
1.41 Crore           3
3.15 Crore           3
2.79 Crore           3
3.85 Crore           3
2.28 Crore           3
34 Lac               3
1.63 Crore           3
94 Lac               3
1.09 Crore           3
4.2 Crore            3
1.88 Crore           3
2.33 Crore           3
2.23 Crore           2
1.46 Crore           2
77.5 Lac             2
53.5 Lac             2
4.49 Crore           2
2.58 Crore           2
6.2 Crore            2
8.5 Crore            2
2.14 Crore           2
27.1 Lac             2
53 Lac               2
2.52 Crore           2
8 Crore              2
2.41 Crore           2
2.57 Crore           2
56.2 Lac             2
3.55 Crore           2
1.87 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
4.26 Crore           2
2.13 Crore           2
2.02 Crore           2
5.2 Crore            2
14 Crore             2
2.87 Crore           2
2.99 Crore           2
2.26 Crore           2
1.56 Crore           2
5.7 Crore            2
52.56 Lac            2
87.5 Lac             2
71 Lac               2
3.29 Crore           2
59 Lac               2
2.91 Crore           2
31.5 Lac             2
41 Lac               2
98.5 Lac             2
2.17 Crore           2
25.5 Lac             2
4.55 Crore           2
7.5 Crore            2
27.75 Lac            2
4.45 Crore           2
4.7 Crore            2
2.04 Crore           2
11 Crore             2
88.5 Lac             2
54.8 Lac             1
63.4 Lac             1
82.5 Lac             1
3.78 Crore           1
2.06 Crore           1
2.07 Crore           1
3.98 Crore           1
7.4 Crore            1
4.02 Crore           1
2.64 Crore           1
44 Lac               1
37.1 Lac             1
97.5 Lac             1
2.38 Crore           1
2.49 Crore           1
97.04 Lac            1
98.88 Lac            1
2.32 Crore           1
4.21 Crore           1
4.16 Crore           1
15 Crore             1
4.52 Crore           1
89.77 Lac            1
73.53 Lac            1
26.5 Lac             1
26.9 Lac             1
1.84 Crore           1
8.44 Crore           1
68.85 Lac            1
39.5 Lac             1
13.2 Crore           1
2.92 Crore           1
61 Lac               1
64.45 Lac            1
2.69 Crore           1
3.99 Crore           1
2.96 Crore           1
57 Lac               1
95.5 Lac             1
37.5 Lac             1
96.07 Lac            1
94.5 Lac             1
29.8 Lac             1
19 Lac               1
88.4 Lac             1
6.02 Crore           1
32.5 Lac             1
7.9 Crore            1
70.85 Lac            1
3.23 Crore           1
40.3 Lac             1
3.72 Crore           1
94.99 Lac            1
1.86 Crore           1
2.54 Crore           1
9 Crore              1
7.52 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
9.95 Crore           1
9.2 Crore            1
86.92 Lac            1
49.5 Lac             1
16 Lac               1
2.44 Crore           1
2.86 Crore           1
1.97 Crore           1
1.53 Crore           1
7.8 Crore            1
4.4 Crore            1
1.74 Crore           1
2.72 Crore           1
5.31 Crore           1
3.19 Crore           1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
2.21 Crore           1
2.63 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
4.95 Crore           1
54.99 Lac            1
2.82 Crore           1
7.15 Crore           1
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
11.25 Crore          1
98.1 Lac             1
55.5 Lac             1
9.3 Crore            1
2.77 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
47.5 Lac             1
42.5 Lac             1
1.11 Crore           1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
5.15 Crore           1
1.06 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
9.14 Crore           1
62.5 Lac             1
Name: count, dtype: int64

In [155]:
df.shape

(3007, 17)

In [156]:
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.5 Crore           59
1.2 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.55 Crore          40
1.9 Crore           40
75 Lac              38
1.65 Crore          38
1.8 Crore           37
1.7 Crore           37
80 Lac              36
2.2 Crore           34
50 Lac              33
1.15 Crore          33
1.45 Crore          31
85 Lac              31
1.05 Crore          30
2.5 Crore           29
60 Lac              29
40 Lac              29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
2.35 Crore          23
1.85 Crore          23
3 Crore             22
70 Lac              21
55 Lac              20
2.25 Crore          20
3.5 Crore           19
2.4 Crore           18
2.3 Crore           18
30 Lac              17
2.65 Crore          16
2.6 Crore           15
1.38 Crore          15
2.45 Crore          14
3.4 Crore           14
2.15 Crore          14
1.32 Crore          13
3.25 Crore          13
78 Lac              13
92 Lac              13
82 Lac              13
38 Lac              13
2.7 Crore           13
1.95 Crore          12
1.42 Crore          12
5 Crore             12
42 Lac              12
2.8 Crore           12
88 Lac              11
32 Lac              11
25 Lac              11
1.08 Crore          11
Price on Request    11
28 Lac              10
1.28 Crore          10
87 Lac              10
26 Lac              10
1.78 Crore          10
1.12 Crore          10
2.55 Crore          10
1.68 Crore           9
3.45 Crore           9
36 Lac               9
22 Lac               9
2.05 Crore           9
4 Crore              9
1.72 Crore           9
99 Lac               9
2.85 Crore           9
27 Lac               8
1.76 Crore           8
98 Lac               8
1.18 Crore           8
1.26 Crore           8
1.54 Crore           8
4.25 Crore           8
2.75 Crore           8
3.2 Crore            8
6 Crore              8
48 Lac               8
6.5 Crore            8
20 Lac               8
56 Lac               8
86 Lac               8
1.36 Crore           7
1.27 Crore           7
97 Lac               7
3.7 Crore            7
1.19 Crore           7
3.3 Crore            7
72 Lac               7
2.9 Crore            7
1.29 Crore           7
46 Lac               7
39 Lac               7
1.02 Crore           7
1.99 Crore           7
79 Lac               7
1.59 Crore           6
43 Lac               6
1.49 Crore           6
1.01 Crore           6
2.95 Crore           6
3.9 Crore            6
96 Lac               6
3.65 Crore           6
5.5 Crore            6
1.07 Crore           6
1.98 Crore           6
21 Lac               6
54 Lac               6
1.39 Crore           6
3.35 Crore           6
1.13 Crore           6
71.5 Lac             6
37 Lac               6
4.1 Crore            6
1.34 Crore           6
3.05 Crore           6
1.14 Crore           6
1.16 Crore           6
1.51 Crore           6
1.24 Crore           5
1.33 Crore           5
1.17 Crore           5
2.22 Crore           5
6.75 Crore           5
1.91 Crore           5
1.82 Crore           5
2.78 Crore           5
1.69 Crore           5
1.44 Crore           5
49 Lac               5
3.75 Crore           5
1.92 Crore           5
1.43 Crore           5
66 Lac               5
2.29 Crore           5
1.79 Crore           5
93 Lac               5
1.62 Crore           5
1.83 Crore           5
1.93 Crore           5
4.5 Crore            5
64 Lac               5
2.12 Crore           5
29 Lac               5
24 Lac               5
1.47 Crore           5
68 Lac               5
1.64 Crore           4
2.09 Crore           4
1.37 Crore           4
5.25 Crore           4
3.6 Crore            4
4.3 Crore            4
5.6 Crore            4
1.22 Crore           4
58 Lac               4
4.85 Crore           4
62 Lac               4
1.23 Crore           4
1.77 Crore           4
41.5 Lac             4
1.52 Crore           4
28.5 Lac             4
1.73 Crore           4
33 Lac               4
7 Crore              4
1.31 Crore           4
36.5 Lac             4
1.48 Crore           4
5.9 Crore            4
3.95 Crore           4
6.15 Crore           4
73 Lac               4
1.58 Crore           4
1.71 Crore           4
89 Lac               4
67 Lac               4
31 Lac               4
1.66 Crore           4
74 Lac               4
3.1 Crore            4
2.24 Crore           3
83 Lac               3
72.5 Lac             3
47 Lac               3
2.36 Crore           3
1.21 Crore           3
1.04 Crore           3
4.75 Crore           3
2.03 Crore           3
3.8 Crore            3
64.5 Lac             3
91 Lac               3
5.8 Crore            3
4.8 Crore            3
1.67 Crore           3
2.51 Crore           3
3.49 Crore           3
2.01 Crore           3
2.08 Crore           3
51 Lac               3
52 Lac               3
84 Lac               3
69 Lac               3
1.57 Crore           3
1.41 Crore           3
3.15 Crore           3
2.79 Crore           3
3.85 Crore           3
2.28 Crore           3
34 Lac               3
1.63 Crore           3
94 Lac               3
1.09 Crore           3
4.2 Crore            3
1.88 Crore           3
2.33 Crore           3
2.23 Crore           2
1.46 Crore           2
77.5 Lac             2
53.5 Lac             2
4.49 Crore           2
2.58 Crore           2
6.2 Crore            2
8.5 Crore            2
2.14 Crore           2
27.1 Lac             2
53 Lac               2
2.52 Crore           2
8 Crore              2
2.41 Crore           2
2.57 Crore           2
56.2 Lac             2
3.55 Crore           2
1.87 Crore           2
3.32 Crore           2
3.21 Crore           2
4.6 Crore            2
4.26 Crore           2
2.13 Crore           2
2.02 Crore           2
5.2 Crore            2
14 Crore             2
2.87 Crore           2
2.99 Crore           2
2.26 Crore           2
1.56 Crore           2
5.7 Crore            2
52.56 Lac            2
87.5 Lac             2
71 Lac               2
3.29 Crore           2
59 Lac               2
2.91 Crore           2
31.5 Lac             2
41 Lac               2
98.5 Lac             2
2.17 Crore           2
25.5 Lac             2
4.55 Crore           2
7.5 Crore            2
27.75 Lac            2
4.45 Crore           2
4.7 Crore            2
2.04 Crore           2
11 Crore             2
88.5 Lac             2
54.8 Lac             1
63.4 Lac             1
82.5 Lac             1
3.78 Crore           1
2.06 Crore           1
2.07 Crore           1
3.98 Crore           1
7.4 Crore            1
4.02 Crore           1
2.64 Crore           1
44 Lac               1
37.1 Lac             1
97.5 Lac             1
2.38 Crore           1
2.49 Crore           1
97.04 Lac            1
98.88 Lac            1
2.32 Crore           1
4.21 Crore           1
4.16 Crore           1
15 Crore             1
4.52 Crore           1
89.77 Lac            1
73.53 Lac            1
26.5 Lac             1
26.9 Lac             1
1.84 Crore           1
8.44 Crore           1
68.85 Lac            1
39.5 Lac             1
13.2 Crore           1
2.92 Crore           1
61 Lac               1
64.45 Lac            1
2.69 Crore           1
3.99 Crore           1
2.96 Crore           1
57 Lac               1
95.5 Lac             1
37.5 Lac             1
96.07 Lac            1
94.5 Lac             1
29.8 Lac             1
19 Lac               1
88.4 Lac             1
6.02 Crore           1
32.5 Lac             1
7.9 Crore            1
70.85 Lac            1
3.23 Crore           1
40.3 Lac             1
3.72 Crore           1
94.99 Lac            1
1.86 Crore           1
2.54 Crore           1
9 Crore              1
7.52 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
9.95 Crore           1
9.2 Crore            1
86.92 Lac            1
49.5 Lac             1
16 Lac               1
2.44 Crore           1
2.86 Crore           1
1.97 Crore           1
1.53 Crore           1
7.8 Crore            1
4.4 Crore            1
1.74 Crore           1
2.72 Crore           1
5.31 Crore           1
3.19 Crore           1
4.63 Crore           1
2.98 Crore           1
66.99 Lac            1
4.78 Crore           1
6.16 Crore           1
5.3 Crore            1
2.21 Crore           1
2.63 Crore           1
89.5 Lac             1
2.48 Crore           1
99.5 Lac             1
3.83 Crore           1
95.75 Lac            1
3.46 Crore           1
5.4 Crore            1
55.6 Lac             1
4.95 Crore           1
54.99 Lac            1
2.82 Crore           1
7.15 Crore           1
6.25 Crore           1
29.99 Lac            1
23 Lac               1
31.75 Lac            1
3.87 Crore           1
29.5 Lac             1
3.67 Crore           1
8.25 Crore           1
2.37 Crore           1
4.67 Crore           1
3.39 Crore           1
3.63 Crore           1
2.34 Crore           1
3.79 Crore           1
5.49 Crore           1
6.3 Crore            1
11.25 Crore          1
98.1 Lac             1
55.5 Lac             1
9.3 Crore            1
2.77 Crore           1
2.11 Crore           1
6.1 Crore            1
5.75 Crore           1
10 Crore             1
24.5 Lac             1
17.5 Lac             1
20.5 Lac             1
47.5 Lac             1
42.5 Lac             1
1.11 Crore           1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
90.5 Lac             1
52.5 Lac             1
2.62 Crore           1
4.86 Crore           1
5.15 Crore           1
1.06 Crore           1
26.1 Lac             1
81 Lac               1
8.35 Crore           1
6.44 Crore           1
7.56 Crore           1
4.79 Crore           1
2.97 Crore           1
94.25 Lac            1
80.5 Lac             1
93.75 Lac            1
85.5 Lac             1
68.5 Lac             1
79.9 Lac             1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
35.5 Lac             1
4.94 Crore           1
10.75 Crore          1
9.14 Crore           1
62.5 Lac             1
Name: count, dtype: int64

In [157]:
df = df[df['price'] != "Price on Request"]

In [158]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   society          2995 non-null   object
 2   price            2996 non-null   object
 3   area             2996 non-null   object
 4   areaWithType     2996 non-null   object
 5   bedRoom          2996 non-null   object
 6   bathroom         2996 non-null   object
 7   balcony          2996 non-null   object
 8   additionalRoom   1692 non-null   object
 9   address          2990 non-null   object
 10  floorNum         2994 non-null   object
 11  facing           2122 non-null   object
 12  agePossession    2995 non-null   object
 13  nearbyLocations  2905 non-null   object
 14  description      2996 non-null   object
 15  furnishDetails   2200 non-null   object
 16  features         2589 non-null   object
dtypes: object(17)
memory usage: 421.3+ KB

In [159]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [160]:
df['price']  =df['price'].str.split(' ').apply(treat_price)

In [161]:
df['area'].value_counts()

area
₹ 10,000/sq.ft.     19
₹ 8,000/sq.ft.      16
₹ 12,500/sq.ft.     16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 7,500/sq.ft.      12
₹ 8,333/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       7
₹ 11,111/sq.ft.      6
₹ 5,500/sq.ft.       6
₹ 6,578/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 9,230/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 16,000/sq.ft.      5
₹ 6,500/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 8,888/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 8,571/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 7,692/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 5,600/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 4,615/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 7,641/sq.ft.       5
₹ 4,666/sq.ft.       5
₹ 9,822/sq.ft.       4
₹ 8,432/sq.ft.       4
₹ 4,500/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 4,854/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 16,666/sq.ft.      4
₹ 13,636/sq.ft.      4
₹ 15,000/sq.ft.      4
₹ 8,474/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 8,784/sq.ft.       4
₹ 13,750/sq.ft.      4
₹ 7,317/sq.ft.       4
₹ 15,384/sq.ft.      4
₹ 4,814/sq.ft.       4
₹ 7,496/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 8,108/sq.ft.       4
₹ 8,139/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 6,735/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 9,090/sq.ft.       4
₹ 7,250/sq.ft.       4
₹ 10,383/sq.ft.      4
₹ 8,163/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 7,812/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 9,210/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 8,606/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 9,615/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 5,397/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 8,620/sq.ft.       3
₹ 10,204/sq.ft.      3
₹ 5,735/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 8,080/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 6,387/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 5,319/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 6,476/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,886/sq.ft.       3
₹ 8,450/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 6,818/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 8,750/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 9,904/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 14,000/sq.ft.      3
₹ 7,400/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 6,542/sq.ft.       3
₹ 6,644/sq.ft.       3
₹ 9,972/sq.ft.       3
₹ 8,148/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 14,430/sq.ft.      3
₹ 11,363/sq.ft.      3
₹ 10,500/sq.ft.      3
₹ 7,302/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 13,870/sq.ft.      3
₹ 9,011/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 7,056/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 8,604/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 6,404/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 10,555/sq.ft.      3
₹ 7,467/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 4,513/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 8,897/sq.ft.       2
₹ 14,237/sq.ft.      2
₹ 6,333/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 6,987/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 5,056/sq.ft.       2
₹ 8,433/sq.ft.       2
₹ 8,252/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 13,108/sq.ft.      2
₹ 5,896/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,412/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 8,159/sq.ft.       2
₹ 6,422/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 5,513/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 16,747/sq.ft.      2
₹ 9,020/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 8,290/sq.ft.       2
₹ 9,978/sq.ft.       2
₹ 7,174/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 4,857/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 8,670/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 4,307/sq.ft.       2
₹ 15,551/sq.ft.      2
₹ 8,536/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 7,945/sq.ft.       2
₹ 10,936/sq.ft.      2
₹ 10,516/sq.ft.      2
₹ 16,858/sq.ft.      2
₹ 8,410/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 7,350/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 15,294/sq.ft.      2
₹ 13,991/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 8,279/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 5,528/sq.ft.       2
₹ 11,505/sq.ft.      2
₹ 8,903/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 9,743/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 7,610/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 7,716/sq.ft.       2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 12,022/sq.ft.      2
₹ 8,376/sq.ft.       2
₹ 19,767/sq.ft.      2
₹ 6,839/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 11,336/sq.ft.      2
₹ 7,908/sq.ft.       2
₹ 6,679/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 9,672/sq.ft.       2
₹ 15,416/sq.ft.      2
₹ 9,025/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 6,313/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 5,177/sq.ft.       2
₹ 6,647/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 14,303/sq.ft.      2
₹ 5,820/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 5,980/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 5,828/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 7,223/sq.ft.       2
₹ 6,209/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 6,571/sq.ft.       2
₹ 6,029/sq.ft.       2
₹ 5,808/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 12,444/sq.ft.      2
₹ 5,252/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 4,080/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 10,545/sq.ft.      2
₹ 9,589/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 9,433/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 7,751/sq.ft.       2
₹ 7,758/sq.ft.       2
₹ 15,500/sq.ft.      2
₹ 9,950/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 11,574/sq.ft.      2
₹ 5,674/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 5,683/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 6,655/sq.ft.       2
₹ 7,449/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 9,306/sq.ft.       2
₹ 7,608/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 9,105/sq.ft.       2
₹ 7,185/sq.ft.       2
₹ 7,878/sq.ft.       2
₹ 19,747/sq.ft.      2
₹ 3,695/sq.ft.       2
₹ 6,588/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 5,825/sq.ft.       2
₹ 9,742/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 7,987/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 5,658/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 5,744/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 8,457/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 7,014/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 8,518/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 12,222/sq.ft.      2
₹ 18,518/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 8,814/sq.ft.       2
₹ 6,428/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 6,811/sq.ft.       2
₹ 13,270/sq.ft.      2
₹ 5,284/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 10,666/sq.ft.      2
₹ 6,983/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 9,259/sq.ft.       2
₹ 5,424/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 6,024/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 4,820/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 9,909/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 6,686/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 7,727/sq.ft.       2
₹ 5,189/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 9,851/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 41,245/sq.ft.      2
₹ 6,510/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 7,574/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 5,038/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 10,531/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 6,377/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 10,526/sq.ft.      2
₹ 6,538/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 8,609/sq.ft.       2
₹ 6,217/sq.ft.       2
₹ 10,018/sq.ft.      2
₹ 7,530/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 6,569/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 11,755/sq.ft.      2
₹ 6,593/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 7,782/sq.ft.       2
₹ 9,146/sq.ft.       2
₹ 7,396/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 11,529/sq.ft.      2
₹ 9,062/sq.ft.       2
₹ 5,641/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 6,812/sq.ft.       2
₹ 5,128/sq.ft.       2
₹ 8,582/sq.ft.       2
₹ 18,000/sq.ft.      2
₹ 8,053/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 9,449/sq.ft.       2
₹ 6,338/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 6,178/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 14,257/sq.ft.      2
₹ 5,463/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 6,189/sq.ft.       2
₹ 9,263/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 7,631/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 8,166/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 8,517/sq.ft.       2
₹ 8,072/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 12,782/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 13,333/sq.ft.      2
₹ 9,677/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 6,190/sq.ft.       2
₹ 6,859/sq.ft.       2
₹ 6,134/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 11,700/sq.ft.      2
₹ 6,206/sq.ft.       2
₹ 8,521/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 6,551/sq.ft.       2
₹ 9,333/sq.ft.       2
₹ 7,825/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 58/sq.ft.          2
₹ 10,476/sq.ft.      2
₹ 7,796/sq.ft.       2
₹ 4,651/sq.ft.       2
₹ 6,722/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 13,281/sq.ft.      2
₹ 6,616/sq.ft.       2
₹ 8,206/sq.ft.       2
₹ 17,619/sq.ft.      2
₹ 5,291/sq.ft.       2
₹ 11,516/sq.ft.      2
₹ 5,899/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 14,214/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 7,248/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 7,679/sq.ft.       1
₹ 7,931/sq.ft.       1
₹ 5,739/sq.ft.       1
₹ 8,095/sq.ft.       1
₹ 4,179/sq.ft.       1
₹ 10,306/sq.ft.      1
₹ 8,558/sq.ft.       1
₹ 10,309/sq.ft.      1
₹ 4,106/sq.ft.       1
₹ 6,077/sq.ft.       1
₹ 8,982/sq.ft.       1
₹ 13,953/sq.ft.      1
₹ 10,754/sq.ft.      1
₹ 10,924/sq.ft.      1
₹ 9,531/sq.ft.       1
₹ 13,921/sq.ft.      1
₹ 14,658/sq.ft.      1
₹ 18,688/sq.ft.      1
₹ 17,378/sq.ft.      1
₹ 8,124/sq.ft.       1
₹ 14,632/sq.ft.      1
₹ 9,696/sq.ft.       1
₹ 17,543/sq.ft.      1
₹ 15,262/sq.ft.      1
₹ 12,791/sq.ft.      1
₹ 6,554/sq.ft.       1
₹ 14,358/sq.ft.      1
₹ 9,236/sq.ft.       1
₹ 6,033/sq.ft.       1
₹ 15,560/sq.ft.      1
₹ 12,009/sq.ft.      1
₹ 14,603/sq.ft.      1
₹ 3,664/sq.ft.       1
₹ 5,813/sq.ft.       1
₹ 6,485/sq.ft.       1
₹ 8,494/sq.ft.       1
₹ 20,666/sq.ft.      1
₹ 12,272/sq.ft.      1
₹ 3,650/sq.ft.       1
₹ 22,222/sq.ft.      1
₹ 3,713/sq.ft.       1
₹ 22,346/sq.ft.      1
₹ 11,209/sq.ft.      1
₹ 9,002/sq.ft.       1
₹ 9,912/sq.ft.       1
₹ 4,545/sq.ft.       1
₹ 6,194/sq.ft.       1
₹ 6,319/sq.ft.       1
₹ 15,102/sq.ft.      1
₹ 4,886/sq.ft.       1
₹ 9/sq.ft.           1
₹ 4,108/sq.ft.       1
₹ 5,296/sq.ft.       1
₹ 23,344/sq.ft.      1
₹ 15,124/sq.ft.      1
₹ 4,375/sq.ft.       1
₹ 6,849/sq.ft.       1
₹ 5,621/sq.ft.       1
₹ 8,986/sq.ft.       1
₹ 18,392/sq.ft.      1
₹ 6,881/sq.ft.       1
₹ 7,779/sq.ft.       1
₹ 7,164/sq.ft.       1
₹ 9,219/sq.ft.       1
₹ 4,971/sq.ft.       1
₹ 11,407/sq.ft.      1
₹ 11,497/sq.ft.      1
₹ 10,094/sq.ft.      1
₹ 4,219/sq.ft.       1
₹ 7,988/sq.ft.       1
₹ 11,074/sq.ft.      1
₹ 10,483/sq.ft.      1
₹ 9,076/sq.ft.       1
₹ 8,674/sq.ft.       1
₹ 14,783/sq.ft.      1
₹ 14,680/sq.ft.      1
₹ 10,408/sq.ft.      1
₹ 10,257/sq.ft.      1
₹ 10,017/sq.ft.      1
₹ 13,425/sq.ft.      1
₹ 10,031/sq.ft.      1
₹ 8,349/sq.ft.       1
₹ 7,917/sq.ft.       1
₹ 10,101/sq.ft.      1
₹ 6,272/sq.ft.       1
₹ 10,172/sq.ft.      1
₹ 20,707/sq.ft.      1
₹ 10,888/sq.ft.      1
₹ 11,094/sq.ft.      1
₹ 9,714/sq.ft.       1
₹ 11,854/sq.ft.      1
₹ 6,648/sq.ft.       1
₹ 13,936/sq.ft.      1
₹ 9,130/sq.ft.       1
₹ 591/sq.ft.         1
₹ 4,941/sq.ft.       1
₹ 3,671/sq.ft.       1
₹ 10,627/sq.ft.      1
₹ 7,066/sq.ft.       1
₹ 11,869/sq.ft.      1
₹ 7,227/sq.ft.       1
₹ 5,904/sq.ft.       1
₹ 17,271/sq.ft.      1
₹ 7,006/sq.ft.       1
₹ 9,264/sq.ft.       1
₹ 9,370/sq.ft.       1
₹ 13,522/sq.ft.      1
₹ 9,380/sq.ft.       1
₹ 10,452/sq.ft.      1
₹ 7,068/sq.ft.       1
₹ 6,256/sq.ft.       1
₹ 8,026/sq.ft.       1
₹ 8,953/sq.ft.       1
₹ 11,178/sq.ft.      1
₹ 12,489/sq.ft.      1
₹ 14,379/sq.ft.      1
₹ 4,729/sq.ft.       1
₹ 11,538/sq.ft.      1
₹ 7,561/sq.ft.       1
₹ 4,933/sq.ft.       1
₹ 6,176/sq.ft.       1
₹ 12,420/sq.ft.      1
₹ 7,293/sq.ft.       1
₹ 5,329/sq.ft.       1
₹ 6,751/sq.ft.       1
₹ 16,230/sq.ft.      1
₹ 11,559/sq.ft.      1
₹ 10,903/sq.ft.      1
₹ 9,519/sq.ft.       1
₹ 15,901/sq.ft.      1
₹ 5,950/sq.ft.       1
₹ 9,513/sq.ft.       1
₹ 6,778/sq.ft.       1
₹ 5,041/sq.ft.       1
₹ 8,554/sq.ft.       1
₹ 8,487/sq.ft.       1
₹ 7,654/sq.ft.       1
₹ 15,130/sq.ft.      1
₹ 8,622/sq.ft.       1
₹ 5,910/sq.ft.       1
₹ 10,578/sq.ft.      1
₹ 11,061/sq.ft.      1
₹ 4,587/sq.ft.       1
₹ 10,656/sq.ft.      1
₹ 7,360/sq.ft.       1
₹ 11,605/sq.ft.      1
₹ 5,590/sq.ft.       1
₹ 6,926/sq.ft.       1
₹ 10,134/sq.ft.      1
₹ 9,843/sq.ft.       1
₹ 11,190/sq.ft.      1
₹ 13,575/sq.ft.      1
₹ 8,120/sq.ft.       1
₹ 9,569/sq.ft.       1
₹ 14,795/sq.ft.      1
₹ 6,951/sq.ft.       1
₹ 11,944/sq.ft.      1
₹ 9,136/sq.ft.       1
₹ 14,267/sq.ft.      1
₹ 8,737/sq.ft.       1
₹ 4,927/sq.ft.       1
₹ 10,071/sq.ft.      1
₹ 6,905/sq.ft.       1
₹ 3,516/sq.ft.       1
₹ 6,346/sq.ft.       1
₹ 4,821/sq.ft.       1
₹ 9,583/sq.ft.       1
₹ 9,639/sq.ft.       1
₹ 9,252/sq.ft.       1
₹ 5,076/sq.ft.       1
₹ 13,480/sq.ft.      1
₹ 11,989/sq.ft.      1
₹ 8,052/sq.ft.       1
₹ 7,760/sq.ft.       1
₹ 8,707/sq.ft.       1
₹ 6,998/sq.ft.       1
₹ 10,773/sq.ft.      1
₹ 8,907/sq.ft.       1
₹ 8,920/sq.ft.       1
₹ 6,083/sq.ft.       1
₹ 6,113/sq.ft.       1
₹ 6,894/sq.ft.       1
₹ 7,321/sq.ft.       1
₹ 9,734/sq.ft.       1
₹ 4,869/sq.ft.       1
₹ 8,446/sq.ft.       1
₹ 7,547/sq.ft.       1
₹ 4,579/sq.ft.       1
₹ 5,443/sq.ft.       1
₹ 8,856/sq.ft.       1
₹ 8,840/sq.ft.       1
₹ 13,296/sq.ft.      1
₹ 8,111/sq.ft.       1
₹ 5,479/sq.ft.       1
₹ 4,931/sq.ft.       1
₹ 10,723/sq.ft.      1
₹ 7,714/sq.ft.       1
₹ 4,458/sq.ft.       1
₹ 7,769/sq.ft.       1
₹ 4,868/sq.ft.       1
₹ 8,040/sq.ft.       1
₹ 7,103/sq.ft.       1
₹ 5,931/sq.ft.       1
₹ 8,297/sq.ft.       1
₹ 8,790/sq.ft.       1
₹ 9,664/sq.ft.       1
₹ 11,923/sq.ft.      1
₹ 6,979/sq.ft.       1
₹ 11,386/sq.ft.      1
₹ 11,423/sq.ft.      1
₹ 15,360/sq.ft.      1
₹ 4,923/sq.ft.       1
₹ 6,159/sq.ft.       1
₹ 9,125/sq.ft.       1
₹ 8,557/sq.ft.       1
₹ 8,042/sq.ft.       1
₹ 8,734/sq.ft.       1
₹ 11,442/sq.ft.      1
₹ 13,984/sq.ft.      1
₹ 6,556/sq.ft.       1
₹ 4,404/sq.ft.       1
₹ 16,445/sq.ft.      1
₹ 7,262/sq.ft.       1
₹ 5,952/sq.ft.       1
₹ 6,562/sq.ft.       1
₹ 11,725/sq.ft.      1
₹ 5,965/sq.ft.       1
₹ 6,587/sq.ft.       1
₹ 7,010/sq.ft.       1
₹ 5,625/sq.ft.       1
₹ 10,418/sq.ft.      1
₹ 6,137/sq.ft.       1
₹ 11,600/sq.ft.      1
₹ 5,571/sq.ft.       1
₹ 7,171/sq.ft.       1
₹ 11,525/sq.ft.      1
₹ 15,982/sq.ft.      1
₹ 8,266/sq.ft.       1
₹ 14,838/sq.ft.      1
₹ 7,402/sq.ft.       1
₹ 5,958/sq.ft.       1
₹ 6,768/sq.ft.       1
₹ 8,700/sq.ft.       1
₹ 10,482/sq.ft.      1
₹ 5,413/sq.ft.       1
₹ 5,720/sq.ft.       1
₹ 4,778/sq.ft.       1
₹ 9,856/sq.ft.       1
₹ 11,963/sq.ft.      1
₹ 10,697/sq.ft.      1
₹ 7,453/sq.ft.       1
₹ 7,882/sq.ft.       1
₹ 8,802/sq.ft.       1
₹ 6,435/sq.ft.       1
₹ 10,058/sq.ft.      1
₹ 8,387/sq.ft.       1
₹ 7,872/sq.ft.       1
₹ 8,404/sq.ft.       1
₹ 11,741/sq.ft.      1
₹ 13,177/sq.ft.      1
₹ 7,951/sq.ft.       1
₹ 8,264/sq.ft.       1
₹ 10,205/sq.ft.      1
₹ 13,989/sq.ft.      1
₹ 11,654/sq.ft.      1
₹ 11,346/sq.ft.      1
₹ 8,123/sq.ft.       1
₹ 6,502/sq.ft.       1
₹ 11,251/sq.ft.      1
₹ 19,943/sq.ft.      1
₹ 20,995/sq.ft.      1
₹ 9,371/sq.ft.       1
₹ 17,729/sq.ft.      1
₹ 10,283/sq.ft.      1
₹ 9,701/sq.ft.       1
₹ 9,102/sq.ft.       1
₹ 9,459/sq.ft.       1
₹ 17,691/sq.ft.      1
₹ 4,637/sq.ft.       1
₹ 8,347/sq.ft.       1
₹ 10,491/sq.ft.      1
₹ 10,375/sq.ft.      1
₹ 9,016/sq.ft.       1
₹ 8,850/sq.ft.       1
₹ 10,163/sq.ft.      1
₹ 6,870/sq.ft.       1
₹ 11,920/sq.ft.      1
₹ 8,240/sq.ft.       1
₹ 6,552/sq.ft.       1
₹ 5,265/sq.ft.       1
₹ 10,004/sq.ft.      1
₹ 7,891/sq.ft.       1
₹ 11,276/sq.ft.      1
₹ 9,218/sq.ft.       1
₹ 2,666/sq.ft.       1
₹ 6,022/sq.ft.       1
₹ 8,970/sq.ft.       1
₹ 2,051/sq.ft.       1
₹ 6,914/sq.ft.       1
₹ 8,522/sq.ft.       1
₹ 10,815/sq.ft.      1
₹ 6,601/sq.ft.       1
₹ 9,745/sq.ft.       1
₹ 5,495/sq.ft.       1
₹ 4,478/sq.ft.       1
₹ 5,719/sq.ft.       1
₹ 7,604/sq.ft.       1
₹ 12,912/sq.ft.      1
₹ 13,126/sq.ft.      1
₹ 4,512/sq.ft.       1
₹ 5,777/sq.ft.       1
₹ 4,694/sq.ft.       1
₹ 6,598/sq.ft.       1
₹ 4,591/sq.ft.       1
₹ 14,652/sq.ft.      1
₹ 3,692/sq.ft.       1
₹ 6,185/sq.ft.       1
₹ 5,220/sq.ft.       1
₹ 13,608/sq.ft.      1
₹ 14,009/sq.ft.      1
₹ 5,039/sq.ft.       1
₹ 4,325/sq.ft.       1
₹ 5,013/sq.ft.       1
₹ 19,444/sq.ft.      1
₹ 5,666/sq.ft.       1
₹ 4,453/sq.ft.       1
₹ 7,422/sq.ft.       1
₹ 8,515/sq.ft.       1
₹ 3,600/sq.ft.       1
₹ 4,977/sq.ft.       1
₹ 9,879/sq.ft.       1
₹ 4,250/sq.ft.       1
₹ 7,389/sq.ft.       1
₹ 4,716/sq.ft.       1
₹ 5,933/sq.ft.       1
₹ 15,178/sq.ft.      1
₹ 13,975/sq.ft.      1
₹ 7,754/sq.ft.       1
₹ 5,261/sq.ft.       1
₹ 8,990/sq.ft.       1
₹ 14,754/sq.ft.      1
₹ 12,408/sq.ft.      1
₹ 4,470/sq.ft.       1
₹ 14,551/sq.ft.      1
₹ 6,526/sq.ft.       1
₹ 15,267/sq.ft.      1
₹ 2,638/sq.ft.       1
₹ 5,583/sq.ft.       1

In [162]:
str = "₹ 6,224/sq.ft."
str.split('/')[0].replace(',', "").replace('₹', '').strip()

'6224'

In [165]:
df['area'] = df['area'].str.split('/').str.get(0).str.replace(",", '').str.replace("₹", "").str.strip().astype(float)

In [167]:
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te..."
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   society          2995 non-null   object
 2   price            2996 non-null   float64
 3   price_per_sqft   2996 non-null   float64
 4   areaWithType     2996 non-null   object
 5   bedRoom          2996 non-null   object
 6   bathroom         2996 non-null   object
 7   balcony          2996 non-null   object
 8   additionalRoom   1692 non-null   object
 9   address          2990 non-null   object
 10  floorNum         2994 non-null   object
 11  facing           2122 non-null   object
 12  agePossession    2995 non-null   object
 13  nearbyLocations  2905 non-null   object
 14  description      2996 non-null   object
 15  furnishDetails   2200 non-null   object
 16  features         2589 non-null   object
dtypes: float64(2), object(15)
memory usage: 421.3+ KB

In [178]:
df['balcony'].isnull().sum()

0

In [174]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype(int)

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   society          2995 non-null   object
 2   price            2996 non-null   float64
 3   price_per_sqft   2996 non-null   float64
 4   areaWithType     2996 non-null   object
 5   bedRoom          2996 non-null   int32
 6   bathroom         2996 non-null   object
 7   balcony          2996 non-null   object
 8   additionalRoom   1692 non-null   object
 9   address          2990 non-null   object
 10  floorNum         2994 non-null   object
 11  facing           2122 non-null   object
 12  agePossession    2995 non-null   object
 13  nearbyLocations  2905 non-null   object
 14  description      2996 non-null   object
 15  furnishDetails   2200 non-null   object
 16  features         2589 non-null   object
dtypes: float64(2), int32(1), object(14)
memory usage: 409.6+ KB

In [190]:
df['balcony'] =  df['balcony'].str.split(' ').str.get(0).str.replace('+', '').str.replace('No', '0').astype('Int16')

In [191]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   society          2995 non-null   object
 2   price            2996 non-null   float64
 3   price_per_sqft   2996 non-null   float64
 4   areaWithType     2996 non-null   object
 5   bedRoom          2996 non-null   int32
 6   bathroom         2996 non-null   object
 7   balcony          2996 non-null   Int16
 8   additionalRoom   1692 non-null   object
 9   address          2990 non-null   object
 10  floorNum         2994 non-null   object
 11  facing           2122 non-null   object
 12  agePossession    2995 non-null   object
 13  nearbyLocations  2905 non-null   object
 14  description      2996 non-null   object
 15  furnishDetails   2200 non-null   object
 16  features         2589 non-null   object
dtypes: Int16(1), float64(2), int32(1), object(13)
memory usage: 395.0+ KB

In [197]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype(int)

In [198]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   society          2995 non-null   object
 2   price            2996 non-null   float64
 3   price_per_sqft   2996 non-null   float64
 4   areaWithType     2996 non-null   object
 5   bedRoom          2996 non-null   int32
 6   bathroom         2996 non-null   int32
 7   balcony          2996 non-null   Int16
 8   additionalRoom   1692 non-null   object
 9   address          2990 non-null   object
 10  floorNum         2994 non-null   object
 11  facing           2122 non-null   object
 12  agePossession    2995 non-null   object
 13  nearbyLocations  2905 non-null   object
 14  description      2996 non-null   object
 15  furnishDetails   2200 non-null   object
 16  features         2589 non-null   object
dtypes: Int16(1), float64(2), int32(2), object(12)
memory usage: 383.3+ KB

In [199]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te..."
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN

In [212]:
import re

In [215]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).str.replace('Ground', '0').str.replace('Basement', '0').str.replace('Lower', '0').str.extract(r'(\d+)')

In [224]:
df['society'] = (
    df['society']
    .str.replace(r'\d+(\.\d+)?\s?★', '', regex=True)
    .str.strip()
    .str.lower())
df['society'].value_counts().shape

(598,)

In [231]:
df['facing'].value_counts()

facing
DK            874
North-East    505
East          489
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [232]:
df['facing'].isnull().sum()

0

In [230]:
df['facing'].fillna('DK', inplace=True)

In [233]:
df.insert(loc=4,column='area',value=round((df['price']*10000000)/df['price_per_sqft']))

In [235]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12,DK,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,DK,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te..."
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,DK,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN

In [236]:
df.insert(loc=1, column='type', value='flat')

In [238]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2996 entries, 0 to 3016
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    2996 non-null   object
 1   type             2996 non-null   object
 2   society          2995 non-null   object
 3   price            2996 non-null   float64
 4   price_per_sqft   2996 non-null   float64
 5   area             2996 non-null   float64
 6   areaWithType     2996 non-null   object
 7   bedRoom          2996 non-null   int32
 8   bathroom         2996 non-null   int32
 9   balcony          2996 non-null   Int16
 10  additionalRoom   1692 non-null   object
 11  address          2990 non-null   object
 12  floorNum         2994 non-null   object
 13  facing           2996 non-null   object
 14  agePossession    2995 non-null   object
 15  nearbyLocations  2905 non-null   object
 16  description      2996 non-null   object
 17  furnishDetails   2200 non-null   object
 18  features         2589 non-null   object
dtypes: Int16(1), float64(3), int32(2), object(13)
memory usage: 430.1+ KB