In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv('data_houses.csv')

In [4]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    1044 non-null   object
 1   link             1044 non-null   object
 2   society          453 non-null    object
 3   price            968 non-null    object
 4   rate             1005 non-null   object
 5   area             1044 non-null   object
 6   areaWithType     987 non-null    object
 7   bedRoom          987 non-null    object
 8   bathroom         987 non-null    object
 9   balcony          987 non-null    object
 10  additionalRoom   589 non-null    object
 11  address          1031 non-null   object
 12  noOfFloor        967 non-null    object
 13  facing           674 non-null    object
 14  agePossession    987 non-null    object
 15  nearbyLocations  913 non-null    object
 16  description      1036 non-null   object
 17  furnishDetails   743 non-null    object
 18  features         674 non-null    object
 19  rating           907 non-null    object
 20  property_id      1036 non-null   object
dtypes: object(21)
memory usage: 171.4+ KB

In [6]:
df.isnull().sum()

property_name        0
link                 0
society            591
price               76
rate                39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     455
address             13
noOfFloor           77
facing             370
agePossession       57
nearbyLocations    131
description          8
furnishDetails     301
features           370
rating             137
property_id          8
dtype: int64

In [7]:
df.drop(['link', 'rating', 'property_id'], axis =1 , inplace=True)

In [8]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [9]:
df.isnull().sum()

property_name        0
society            591
price               76
rate                39
area                 0
areaWithType        57
bedRoom             57
bathroom            57
balcony             57
additionalRoom     455
address             13
noOfFloor           77
facing             370
agePossession       57
nearbyLocations    131
description          8
furnishDetails     301
features           370
dtype: int64

In [10]:
df.dropna(subset='price', inplace=True)

In [11]:
def treat_price(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [12]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25 Crore,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.7 Crore,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.1 Crore,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5 Crore,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3 Crore,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [13]:
df.price.value_counts()

price
3.5 Crore           19
5.5 Crore           17
6.5 Crore           16
6 Crore             14
8 Crore             13
5 Crore             13
4.5 Crore           13
50 Lac              13
70 Lac              13
75 Lac              13
85 Lac              12
2.5 Crore           12
8.5 Crore           12
7 Crore             12
4 Crore             11
1.5 Crore           11
60 Lac              10
45 Lac              10
Price on Request    10
90 Lac              10
10 Crore            10
9 Crore             10
2.25 Crore          10
80 Lac               9
1.7 Crore            9
9.5 Crore            9
1.1 Crore            9
12 Crore             9
2 Crore              9
1.6 Crore            8
4.6 Crore            8
1 Crore              8
6.75 Crore           8
11 Crore             8
3.75 Crore           8
1.2 Crore            7
2.1 Crore            7
1.3 Crore            7
65 Lac               7
95 Lac               7
55 Lac               7
40 Lac               7
1.35 Crore           7
12.5 Crore           7
1.45 Crore           6
2.95 Crore           6
7.5 Crore            6
5.7 Crore            6
4.25 Crore           6
3.25 Crore           6
13.5 Crore           6
5.6 Crore            6
2.75 Crore           6
6.25 Crore           6
1.15 Crore           6
7.25 Crore           6
10.5 Crore           6
16 Crore             6
3.6 Crore            6
35 Lac               5
5.75 Crore           5
4.75 Crore           5
15 Crore             5
2.8 Crore            5
3 Crore              5
17 Crore             5
1.25 Crore           5
1.8 Crore            5
38 Lac               5
8.25 Crore           5
9.25 Crore           4
18 Crore             4
4.35 Crore           4
2.4 Crore            4
42 Lac               4
1.65 Crore           4
4.7 Crore            4
37 Lac               4
5.25 Crore           4
1.4 Crore            4
13 Crore             4
8.4 Crore            4
6.8 Crore            4
11.5 Crore           4
3.2 Crore            4
5.8 Crore            4
3.3 Crore            4
62 Lac               3
7.2 Crore            3
49 Lac               3
3.85 Crore           3
4.45 Crore           3
82 Lac               3
3.55 Crore           3
1.16 Crore           3
2.3 Crore            3
1.9 Crore            3
34 Lac               3
1.55 Crore           3
20 Crore             3
2.2 Crore            3
3.1 Crore            3
5.65 Crore           3
2.9 Crore            3
1.95 Crore           3
5.15 Crore           3
92 Lac               3
6.4 Crore            3
1.85 Crore           3
2.55 Crore           3
4.3 Crore            3
7.35 Crore           3
19 Crore             3
6.95 Crore           3
3.4 Crore            3
32 Lac               3
4.95 Crore           2
58 Lac               2
58.25 Lac            2
14 Crore             2
2.15 Crore           2
9.9 Crore            2
89 Lac               2
1.05 Crore           2
3.51 Crore           2
3.15 Crore           2
3.35 Crore           2
8.49 Crore           2
10.85 Crore          2
5.4 Crore            2
11.95 Crore          2
36 Lac               2
3.65 Crore           2
26 Crore             2
10.55 Crore          2
3.05 Crore           2
7.1 Crore            2
6.3 Crore            2
11.25 Crore          2
15.5 Crore           2
48 Lac               2
11.75 Crore          2
67 Lac               2
19.5 Crore           2
10.45 Crore          2
1.75 Crore           2
7.99 Crore           2
30 Lac               2
66 Lac               2
10.3 Crore           1
2.47 Crore           1
3.7 Crore            1
7.3 Crore            1
4.15 Crore           1
18.4 Crore           1
22 Crore             1
6.15 Crore           1
4.4 Crore            1
8.45 Crore           1
46.75 Lac            1
9.4 Crore            1
18.5 Crore           1
12.25 Crore          1
27.5 Crore           1
52.75 Lac            1
5.88 Crore           1
8.31 Crore           1
6.21 Crore           1
2.01 Crore           1
3.9 Crore            1
5.1 Crore            1
1.83 Crore           1
99 Lac               1
2.45 Crore           1
2.65 Crore           1
1.18 Crore           1
9.01 Crore           1
9.8 Crore            1
4.99 Crore           1
8.6 Crore            1
9.55 Crore           1
2.35 Crore           1
18.25 Crore          1
5.3 Crore            1
10.8 Crore           1
31.5 Crore           1
4.1 Crore            1
7.65 Crore           1
6.46 Crore           1
6.44 Crore           1
7.8 Crore            1
3.8 Crore            1
7.45 Crore           1
7.42 Crore           1
6.09 Crore           1
15.1 Crore           1
9.85 Crore           1
1.27 Crore           1
1.04 Crore           1
11.29 Crore          1
4.31 Crore           1
11.58 Crore          1
8.48 Crore           1
8.2 Crore            1
5.51 Crore           1
3.49 Crore           1
2.99 Crore           1
9.19 Crore           1
1.64 Crore           1
9.35 Crore           1
4.05 Crore           1
8.75 Crore           1
23 Crore             1
8.9 Crore            1
7.85 Crore           1
25 Crore             1
2.68 Crore           1
2.7 Crore            1
4.49 Crore           1
65.8 Lac             1
8.81 Crore           1
55.11 Lac            1
7.5 Lac              1
2.58 Crore           1
8.95 Crore           1
13.2 Crore           1
51 Lac               1
53 Lac               1
63 Lac               1
1.72 Crore           1
78 Lac               1
1.52 Crore           1
5.46 Crore           1
52 Lac               1
10.56 Crore          1
4.65 Crore           1
6.1 Crore            1
68 Lac               1
1.07 Crore           1
3.12 Crore           1
7.49 Crore           1
6.81 Crore           1
22 Lac               1
7.05 Crore           1
3.69 Crore           1
11.3 Crore           1
4.02 Crore           1
6.6 Crore            1
5.35 Crore           1
5.85 Crore           1
5.9 Crore            1
6.2 Crore            1
3.93 Crore           1
8.7 Crore            1
7.69 Crore           1
15.5 Lac             1
8.8 Crore            1
4.12 Crore           1
1.87 Crore           1
12.39 Crore          1
7.6 Crore            1
5.2 Crore            1
42.75 Lac            1
47 Lac               1
61 Lac               1
1.34 Crore           1
46 Lac               1
2.6 Crore            1
3.87 Crore           1
1.39 Crore           1
59 Lac               1
27 Lac               1
8.1 Crore            1
14.75 Crore          1
9.54 Crore           1
17.3 Crore           1
18.9 Crore           1
24 Crore             1
7.46 Crore           1
59.95 Lac            1
3.99 Crore           1
18.02 Crore          1
10.75 Crore          1
96 Lac               1
24 Lac               1
71 Lac               1
52.5 Lac             1
1.44 Crore           1
3.71 Crore           1
18 Lac               1
3.08 Crore           1
29 Lac               1
44 Lac               1
13 Lac               1
83 Lac               1
98 Lac               1
47.5 Lac             1
3.09 Crore           1
74 Lac               1
69 Lac               1
2.43 Crore           1
2.98 Crore           1
Name: count, dtype: int64

In [14]:
df= df[df["price"] != "Price on Request"]

In [15]:
df['price'].value_counts()

price
3.5 Crore      19
5.5 Crore      17
6.5 Crore      16
6 Crore        14
8 Crore        13
5 Crore        13
4.5 Crore      13
75 Lac         13
70 Lac         13
50 Lac         13
2.5 Crore      12
85 Lac         12
7 Crore        12
8.5 Crore      12
1.5 Crore      11
4 Crore        11
45 Lac         10
90 Lac         10
10 Crore       10
9 Crore        10
60 Lac         10
2.25 Crore     10
9.5 Crore       9
1.7 Crore       9
1.1 Crore       9
2 Crore         9
80 Lac          9
12 Crore        9
4.6 Crore       8
11 Crore        8
3.75 Crore      8
6.75 Crore      8
1 Crore         8
1.6 Crore       8
1.2 Crore       7
1.3 Crore       7
55 Lac          7
65 Lac          7
2.1 Crore       7
12.5 Crore      7
95 Lac          7
40 Lac          7
1.35 Crore      7
6.25 Crore      6
3.6 Crore       6
7.5 Crore       6
1.45 Crore      6
3.25 Crore      6
10.5 Crore      6
5.7 Crore       6
4.25 Crore      6
16 Crore        6
2.75 Crore      6
7.25 Crore      6
1.15 Crore      6
5.6 Crore       6
13.5 Crore      6
2.95 Crore      6
35 Lac          5
5.75 Crore      5
4.75 Crore      5
15 Crore        5
2.8 Crore       5
3 Crore         5
17 Crore        5
1.25 Crore      5
1.8 Crore       5
38 Lac          5
8.25 Crore      5
9.25 Crore      4
18 Crore        4
4.35 Crore      4
2.4 Crore       4
42 Lac          4
1.65 Crore      4
4.7 Crore       4
37 Lac          4
5.25 Crore      4
1.4 Crore       4
11.5 Crore      4
3.2 Crore       4
5.8 Crore       4
8.4 Crore       4
6.8 Crore       4
13 Crore        4
3.3 Crore       4
34 Lac          3
1.9 Crore       3
82 Lac          3
20 Crore        3
4.45 Crore      3
1.16 Crore      3
3.55 Crore      3
5.65 Crore      3
49 Lac          3
2.55 Crore      3
62 Lac          3
2.9 Crore       3
7.2 Crore       3
2.3 Crore       3
2.2 Crore       3
7.35 Crore      3
1.95 Crore      3
4.3 Crore       3
1.55 Crore      3
3.85 Crore      3
3.1 Crore       3
32 Lac          3
1.85 Crore      3
3.4 Crore       3
6.4 Crore       3
19 Crore        3
5.15 Crore      3
6.95 Crore      3
92 Lac          3
58.25 Lac       2
3.15 Crore      2
8.49 Crore      2
3.35 Crore      2
58 Lac          2
3.51 Crore      2
10.85 Crore     2
2.15 Crore      2
14 Crore        2
9.9 Crore       2
1.05 Crore      2
89 Lac          2
4.95 Crore      2
6.3 Crore       2
11.95 Crore     2
19.5 Crore      2
11.25 Crore     2
3.65 Crore      2
66 Lac          2
26 Crore        2
10.55 Crore     2
3.05 Crore      2
7.1 Crore       2
15.5 Crore      2
11.75 Crore     2
48 Lac          2
67 Lac          2
30 Lac          2
36 Lac          2
10.45 Crore     2
1.75 Crore      2
7.99 Crore      2
5.4 Crore       2
8.45 Crore      1
4.4 Crore       1
18.4 Crore      1
22 Crore        1
4.15 Crore      1
3.7 Crore       1
2.47 Crore      1
6.15 Crore      1
7.3 Crore       1
5.1 Crore       1
18.5 Crore      1
9.4 Crore       1
10.3 Crore      1
99 Lac          1
8.31 Crore      1
3.9 Crore       1
2.01 Crore      1
12.25 Crore     1
1.83 Crore      1
27.5 Crore      1
52.75 Lac       1
5.88 Crore      1
6.21 Crore      1
46.75 Lac       1
23 Crore        1
2.65 Crore      1
1.18 Crore      1
9.01 Crore      1
9.8 Crore       1
4.99 Crore      1
8.6 Crore       1
9.55 Crore      1
2.35 Crore      1
18.25 Crore     1
5.3 Crore       1
10.8 Crore      1
31.5 Crore      1
4.1 Crore       1
7.65 Crore      1
6.46 Crore      1
6.44 Crore      1
7.8 Crore       1
3.8 Crore       1
7.45 Crore      1
7.42 Crore      1
6.09 Crore      1
15.1 Crore      1
9.85 Crore      1
1.27 Crore      1
1.04 Crore      1
11.29 Crore     1
4.31 Crore      1
11.58 Crore     1
8.48 Crore      1
8.2 Crore       1
5.51 Crore      1
3.49 Crore      1
2.99 Crore      1
9.19 Crore      1
1.64 Crore      1
9.35 Crore      1
4.05 Crore      1
8.75 Crore      1
8.9 Crore       1
2.45 Crore      1
7.85 Crore      1
25 Crore        1
2.68 Crore      1
2.7 Crore       1
4.49 Crore      1
65.8 Lac        1
8.81 Crore      1
7.49 Crore      1
3.12 Crore      1
7.5 Lac         1
2.58 Crore      1
8.95 Crore      1
13.2 Crore      1
51 Lac          1
53 Lac          1
63 Lac          1
1.72 Crore      1
78 Lac          1
1.52 Crore      1
5.46 Crore      1
52 Lac          1
10.56 Crore     1
4.65 Crore      1
6.1 Crore       1
68 Lac          1
55.11 Lac       1
22 Lac          1
6.81 Crore      1
12.39 Crore     1
61 Lac          1
7.05 Crore      1
3.69 Crore      1
11.3 Crore      1
4.02 Crore      1
6.6 Crore       1
5.35 Crore      1
5.85 Crore      1
5.9 Crore       1
6.2 Crore       1
3.93 Crore      1
8.7 Crore       1
7.69 Crore      1
15.5 Lac        1
8.8 Crore       1
4.12 Crore      1
1.87 Crore      1
1.07 Crore      1
7.6 Crore       1
5.2 Crore       1
42.75 Lac       1
18.02 Crore     1
1.34 Crore      1
46 Lac          1
2.6 Crore       1
3.87 Crore      1
1.39 Crore      1
59 Lac          1
27 Lac          1
8.1 Crore       1
14.75 Crore     1
9.54 Crore      1
17.3 Crore      1
18.9 Crore      1
24 Crore        1
7.46 Crore      1
59.95 Lac       1
3.99 Crore      1
10.75 Crore     1
96 Lac          1
13 Lac          1
29 Lac          1
47 Lac          1
71 Lac          1
52.5 Lac        1
1.44 Crore      1
3.71 Crore      1
18 Lac          1
3.08 Crore      1
24 Lac          1
2.43 Crore      1
44 Lac          1
83 Lac          1
98 Lac          1
47.5 Lac        1
3.09 Crore      1
74 Lac          1
69 Lac          1
2.98 Crore      1
Name: count, dtype: int64

In [16]:
df['price'] = df['price'].str.split(' ').apply(treat_price)

In [17]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25,"₹ 20,115/sq.ft.",(242 sq.m.) Plot Area,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.70,"₹ 105,751/sq.ft.",(50 sq.m.) Plot Area,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.10,"₹ 38,251/sq.ft.",(51 sq.m.) Plot Area,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5.00,"₹ 43,066/sq.ft.",(108 sq.m.) Plot Area,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3.00,"₹ 53,763/sq.ft.",(52 sq.m.) Plot Area,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [18]:
df['area'].value_counts()

area
(301 sq.m.) Plot Area        43
(84 sq.m.) Plot Area         37
(251 sq.m.) Plot Area        30
(167 sq.m.) Plot Area        26
(420 sq.m.) Plot Area        22
(226 sq.m.) Plot Area        20
(418 sq.m.) Plot Area        20
(125 sq.m.) Plot Area        19
(201 sq.m.) Plot Area        17
(180 sq.m.) Plot Area        17
(135 sq.m.) Plot Area        16
(50 sq.m.) Plot Area         16
(209 sq.m.) Plot Area        13
(171 sq.m.) Plot Area        12
(334 sq.m.) Plot Area        11
(33 sq.m.) Plot Area         11
(264 sq.m.) Plot Area        10
(42 sq.m.) Plot Area         10
(220 sq.m.) Plot Area        10
(51 sq.m.) Plot Area          9
(145 sq.m.) Plot Area         9
(136 sq.m.) Plot Area         8
(502 sq.m.) Plot Area         8
(151 sq.m.) Plot Area         8
(293 sq.m.) Plot Area         8
(242 sq.m.) Plot Area         7
(161 sq.m.) Plot Area         7
(134 sq.m.) Plot Area         7
(836 sq.m.) Plot Area         6
(372 sq.m.) Plot Area         6
(5 sq.m.) Plot Area           6
(52 sq.m.) Plot Area          6
(100 sq.m.) Plot Area         6
(241 sq.m.) Plot Area         5
(579 sq.m.) Plot Area         5
(286 sq.m.) Plot Area         5
(42 sq.m.) Built-up Area      5
(350 sq.m.) Plot Area         5
(56 sq.m.) Plot Area          5
(84 sq.m.) Carpet Area        5
(6 sq.m.) Plot Area           5
(253 sq.m.) Plot Area         4
(93 sq.m.) Plot Area          4
(93 sq.m.) Built-up Area      4
(54 sq.m.) Plot Area          4
(279 sq.m.) Built-up Area     4
(650 sq.m.) Built-up Area     4
(7 sq.m.) Plot Area           4
(217 sq.m.) Plot Area         4
(109 sq.m.) Plot Area         4
(316 sq.m.) Plot Area         4
(418 sq.m.) Built-up Area     4
(297 sq.m.) Plot Area         4
(139 sq.m.) Plot Area         3
(460 sq.m.) Plot Area         3
(107 sq.m.) Plot Area         3
(142 sq.m.) Plot Area         3
(268 sq.m.) Plot Area         3
(63 sq.m.) Plot Area          3
(9 sq.m.) Plot Area           3
(98 sq.m.) Plot Area          3
(14 sq.m.) Plot Area          3
(102 sq.m.) Built-up Area     3
(91 sq.m.) Plot Area          3
(22 sq.m.) Plot Area          3
(125 sq.m.) Built-up Area     3
(230 sq.m.) Plot Area         3
(99 sq.m.) Plot Area          3
(144 sq.m.) Plot Area         3
(158 sq.m.) Plot Area         3
(100 sq.m.) Built-up Area     3
(28 sq.m.) Plot Area          3
(84 sq.m.) Built-up Area      3
(140 sq.m.) Plot Area         3
(336 sq.m.) Plot Area         3
(105 sq.m.) Plot Area         3
(37 sq.m.) Plot Area          3
(67 sq.m.) Plot Area          3
(435 sq.m.) Plot Area         3
(223 sq.m.) Plot Area         3
(557 sq.m.) Built-up Area     3
(111 sq.m.) Built-up Area     2
(222 sq.m.) Plot Area         2
(167 sq.m.) Built-up Area     2
(85 sq.m.) Plot Area          2
(149 sq.m.) Built-up Area     2
(132 sq.m.) Built-up Area     2
(139 sq.m.) Built-up Area     2
(301 sq.m.) Built-up Area     2
(59 sq.m.) Plot Area          2
(184 sq.m.) Plot Area         2
(113 sq.m.) Plot Area         2
(299 sq.m.) Plot Area         2
(219 sq.m.) Built-up Area     2
(650 sq.m.) Plot Area         2
(105 sq.m.) Built-up Area     2
(146 sq.m.) Plot Area         2
(115 sq.m.) Plot Area         2
(232 sq.m.) Plot Area         2
(45 sq.m.) Built-up Area      2
(108 sq.m.) Plot Area         2
(44 sq.m.) Plot Area          2
(15 sq.m.) Built-up Area      2
(209 sq.m.) Built-up Area     2
(186 sq.m.) Built-up Area     2
(75 sq.m.) Carpet Area        2
(244 sq.m.) Plot Area         2
(33 sq.m.) Built-up Area      2
(318 sq.m.) Plot Area         2
(34 sq.m.) Plot Area          2
(321 sq.m.) Plot Area         2
(89 sq.m.) Built-up Area      2
(251 sq.m.) Built-up Area     2
(89 sq.m.) Plot Area          2
(166 sq.m.) Plot Area         2
(46 sq.m.) Carpet Area        2
(232 sq.m.) Carpet Area       2
(73 sq.m.) Plot Area          2
(15 sq.m.) Plot Area          2
(25 sq.m.) Plot Area          2
(110 sq.m.) Carpet Area       2
(46 sq.m.) Built-up Area      2
(43 sq.m.) Plot Area          2
(135 sq.m.) Carpet Area       2
(301 sq.m.) Carpet Area       2
(88 sq.m.) Plot Area          2
(70 sq.m.) Built-up Area      2
(121 sq.m.) Built-up Area     2
(372 sq.m.) Built-up Area     2
(521 sq.m.) Plot Area         2
(593 sq.m.) Built-up Area     2
(46 sq.m.) Plot Area          2
(41 sq.m.) Plot Area          2
(376 sq.m.) Plot Area         2
(76 sq.m.) Built-up Area      2
(83 sq.m.) Plot Area          2
(121 sq.m.) Plot Area         2
(5 sq.m.) Built-up Area       2
(681 sq.m.) Built-up Area     1
(138 sq.m.) Built-up Area     1
(195 sq.m.) Carpet Area       1
(207 sq.m.) Carpet Area       1
(354 sq.m.) Plot Area         1
(96 sq.m.) Carpet Area        1
(594 sq.m.) Built-up Area     1
(73 sq.m.) Carpet Area        1
(44 sq.m.) Carpet Area        1
(162 sq.m.) Built-up Area     1
(100 sq.m.) Carpet Area       1
(107 sq.m.) Carpet Area       1
(201 sq.m.) Built-up Area     1
(152 sq.m.) Plot Area         1
(281 sq.m.) Plot Area         1
(353 sq.m.) Built-up Area     1
(102 sq.m.) Carpet Area       1
(66 sq.m.) Plot Area          1
(80 sq.m.) Plot Area          1
(204 sq.m.) Plot Area         1
(79 sq.m.) Plot Area          1
(222 sq.m.) Built-up Area     1
(176 sq.m.) Built-up Area     1
(248 sq.m.) Built-up Area     1
(124 sq.m.) Built-up Area     1
(111 sq.m.) Carpet Area       1
(437 sq.m.) Built-up Area     1
(339 sq.m.) Built-up Area     1
(143 sq.m.) Built-up Area     1
(69 sq.m.) Plot Area          1
(186 sq.m.) Carpet Area       1
(393 sq.m.) Plot Area         1
(130 sq.m.) Plot Area         1
(308 sq.m.) Plot Area         1
(225 sq.m.) Plot Area         1
(510 sq.m.) Plot Area         1
(155 sq.m.) Plot Area         1
(4699 sq.m.) Plot Area        1
(250 sq.m.) Plot Area         1
(450 sq.m.) Plot Area         1
(302 sq.m.) Plot Area         1
(128 sq.m.) Plot Area         1
(181 sq.m.) Plot Area         1
(509 sq.m.) Plot Area         1
(159 sq.m.) Plot Area         1
(234 sq.m.) Plot Area         1
(537 sq.m.) Plot Area         1
(754 sq.m.) Plot Area         1
(176 sq.m.) Plot Area         1
(26 sq.m.) Plot Area          1
(189 sq.m.) Plot Area         1
(466 sq.m.) Built-up Area     1
(288 sq.m.) Plot Area         1
(314 sq.m.) Plot Area         1
(194 sq.m.) Built-up Area     1
(136 sq.m.) Built-up Area     1
(194 sq.m.) Plot Area         1
(443 sq.m.) Plot Area         1
(12 sq.m.) Plot Area          1
(179 sq.m.) Plot Area         1
(168 sq.m.) Plot Area         1
(669 sq.m.) Plot Area         1
(102 sq.m.) Plot Area         1
(60 sq.m.) Plot Area          1
(16 sq.m.) Plot Area          1
(71 sq.m.) Built-up Area      1
(249 sq.m.) Built-up Area     1
(153 sq.m.) Built-up Area     1
(4 sq.m.) Plot Area           1
(75 sq.m.) Built-up Area      1
(401 sq.m.) Plot Area         1
(1003 sq.m.) Plot Area        1
(21 sq.m.) Plot Area          1
(213 sq.m.) Plot Area         1
(590 sq.m.) Built-up Area     1
(196 sq.m.) Plot Area         1
(585 sq.m.) Plot Area         1
(112 sq.m.) Built-up Area     1
(180 sq.m.) Built-up Area     1
(186 sq.m.) Plot Area         1
(23 sq.m.) Plot Area          1
(1049 sq.m.) Plot Area        1
(283 sq.m.) Plot Area         1
(319 sq.m.) Plot Area         1
(422 sq.m.) Plot Area         1
(8 sq.m.) Plot Area           1
(543 sq.m.) Plot Area         1
(305 sq.m.) Plot Area         1
(55 sq.m.) Plot Area          1
(595 sq.m.) Built-up Area     1
(291 sq.m.) Carpet Area       1
(190 sq.m.) Plot Area         1
(207 sq.m.) Built-up Area     1
(25 sq.m.) Built-up Area      1
(242 sq.m.) Built-up Area     1
(133 sq.m.) Plot Area         1
(2415 sq.m.) Plot Area        1
(32 sq.m.) Built-up Area      1
(50 sq.m.) Carpet Area        1
(18 sq.m.) Built-up Area      1
(22 sq.m.) Built-up Area      1
(431 sq.m.) Plot Area         1
(200 sq.m.) Built-up Area     1
(12 sq.m.) Built-up Area      1
(325 sq.m.) Built-up Area     1
(28 sq.m.) Carpet Area        1
(20 sq.m.) Built-up Area      1
(44 sq.m.) Built-up Area      1
(167 sq.m.) Carpet Area       1
(452 sq.m.) Built-up Area     1
(278 sq.m.) Built-up Area     1
(153 sq.m.) Plot Area         1
(134 sq.m.) Carpet Area       1
(121 sq.m.) Carpet Area       1
(367 sq.m.) Built-up Area     1
(809371 sq.m.) Plot Area      1
(90 sq.m.) Plot Area          1
(19 sq.m.) Plot Area          1
(160 sq.m.) Plot Area         1
(92 sq.m.) Plot Area          1
(465 sq.m.) Plot Area         1
(326 sq.m.) Plot Area         1
(316 sq.m.) Built-up Area     1
(302 sq.m.) Carpet Area       1
(63 sq.m.) Built-up Area      1
(104 sq.m.) Built-up Area     1
(471 sq.m.) Plot Area         1
(210 sq.m.) Plot Area         1
(300 sq.m.) Plot Area         1
(70 sq.m.) Plot Area          1
(255 sq.m.) Plot Area         1
(743 sq.m.) Built-up Area     1
(223 sq.m.) Built-up Area     1
(815 sq.m.) Plot Area         1
(254 sq.m.) Plot Area         1
(206 sq.m.) Plot Area         1
(557 sq.m.) Plot Area         1
(743 sq.m.) Plot Area         1
(1254 sq.m.) Plot Area        1
(2592 sq.m.) Plot Area        1
(360 sq.m.) Plot Area         1
(511 sq.m.) Built-up Area     1
(13 sq.m.) Plot Area          1
(64 sq.m.) Plot Area          1
(94 sq.m.) Built-up Area      1
(10 sq.m.) Built-up Area      1
(111 sq.m.) Plot Area         1
(261 sq.m.) Plot Area         1
(260 sq.m.) Carpet Area       1
(339 sq.m.) Plot Area         1
(92 sq.m.) Carpet Area        1
(31 sq.m.) Built-up Area      1
(385 sq.m.) Plot Area         1
(135 sq.m.) Built-up Area     1
(234 sq.m.) Carpet Area       1
(124 sq.m.) Plot Area         1
(93 sq.m.) Carpet Area        1
(163 sq.m.) Built-up Area     1
(49 sq.m.) Plot Area          1
(40 sq.m.) Carpet Area        1
(483 sq.m.) Built-up Area     1
(20064 sq.m.) Plot Area       1
(328 sq.m.) Built-up Area     1
(110 sq.m.) Plot Area         1
(151 sq.m.) Carpet Area       1
(76 sq.m.) Plot Area          1
(40 sq.m.) Plot Area          1
(58 sq.m.) Plot Area          1
(92 sq.m.) Built-up Area      1
(65 sq.m.) Plot Area          1
(117 sq.m.) Plot Area         1
(390 sq.m.) Plot Area         1
(74 sq.m.) Plot Area          1
(174 sq.m.) Plot Area         1
(6062 sq.m.) Carpet Area      1
(49 sq.m.) Carpet Area        1
(52 sq.m.) Built-up Area      1
(188 sq.m.) Built-up Area     1
(5 sq.m.) Carpet Area         1
(117 sq.m.) Built-up Area     1
(98 sq.m.) Built-up Area      1
(7692 sq.m.) Plot Area        1
(47 sq.m.) Plot Area          1
(246 sq.m.) Plot Area         1
(291 sq.m.) Plot Area         1
(177 sq.m.) Plot Area         1
(74 sq.m.) Built-up Area      1
(87 sq.m.) Built-up Area      1
(144 sq.m.) Built-up Area     1
(325 sq.m.) Plot Area         1
(9 sq.m.) Built-up Area       1
(51 sq.m.) Built-up Area      1
(929 sq.m.) Carpet Area       1
(13 sq.m.) Built-up Area      1
(233 sq.m.) Built-up Area     1
(478 sq.m.) Built-up Area     1
(57 sq.m.) Plot Area          1
(132 sq.m.) Plot Area         1
(71 sq.m.) Plot Area          1
(95 sq.m.) Plot Area          1
(158 sq.m.) Built-up Area     1
(340 sq.m.) Built-up Area     1
(24 sq.m.) Plot Area          1
(56 sq.m.) Built-up Area      1
(220 sq.m.) Built-up Area     1
(56 sq.m.) Carpet Area        1
(251 sq.m.) Carpet Area       1
(18 sq.m.) Plot Area          1
(325 sq.m.) Carpet Area       1
(23 sq.m.) Carpet Area        1
(149 sq.m.) Plot Area         1
Name: count, dtype: int64

In [19]:
df['area']

0           (242 sq.m.) Plot Area
1            (50 sq.m.) Plot Area
2            (51 sq.m.) Plot Area
3           (108 sq.m.) Plot Area
4            (52 sq.m.) Plot Area
5           (107 sq.m.) Plot Area
6           (301 sq.m.) Plot Area
7           (418 sq.m.) Plot Area
8           (264 sq.m.) Plot Area
9           (180 sq.m.) Plot Area
10          (125 sq.m.) Plot Area
11          (301 sq.m.) Plot Area
12          (136 sq.m.) Plot Area
13          (420 sq.m.) Plot Area
14          (251 sq.m.) Plot Area
15          (125 sq.m.) Plot Area
16          (334 sq.m.) Plot Area
17           (84 sq.m.) Plot Area
18          (201 sq.m.) Plot Area
19          (268 sq.m.) Plot Area
20          (244 sq.m.) Plot Area
21          (293 sq.m.) Plot Area
22          (301 sq.m.) Plot Area
23          (301 sq.m.) Plot Area
24          (180 sq.m.) Plot Area
25          (251 sq.m.) Plot Area
26          (471 sq.m.) Plot Area
27          (242 sq.m.) Plot Area
28          (220 sq.m.) Plot Area
29          (301 sq.m.) Plot Area
30          (210 sq.m.) Plot Area
31          (251 sq.m.) Plot Area
32          (293 sq.m.) Plot Area
33           (84 sq.m.) Plot Area
34          (134 sq.m.) Plot Area
35          (161 sq.m.) Plot Area
36          (251 sq.m.) Plot Area
37          (300 sq.m.) Plot Area
38          (251 sq.m.) Plot Area
39          (251 sq.m.) Plot Area
40          (167 sq.m.) Plot Area
41           (70 sq.m.) Plot Area
42          (251 sq.m.) Plot Area
43          (251 sq.m.) Plot Area
44          (255 sq.m.) Plot Area
45          (251 sq.m.) Plot Area
46          (167 sq.m.) Plot Area
48          (242 sq.m.) Plot Area
49          (180 sq.m.) Plot Area
50          (145 sq.m.) Plot Area
51          (301 sq.m.) Plot Area
52          (418 sq.m.) Plot Area
53      (593 sq.m.) Built-up Area
54          (136 sq.m.) Plot Area
55          (241 sq.m.) Plot Area
56          (372 sq.m.) Plot Area
57          (135 sq.m.) Plot Area
58          (316 sq.m.) Plot Area
59          (316 sq.m.) Plot Area
60      (743 sq.m.) Built-up Area
61           (84 sq.m.) Plot Area
64        (232 sq.m.) Carpet Area
65          (180 sq.m.) Plot Area
79          (220 sq.m.) Plot Area
80          (286 sq.m.) Plot Area
90          (226 sq.m.) Plot Area
91          (502 sq.m.) Plot Area
101     (223 sq.m.) Built-up Area
106         (209 sq.m.) Plot Area
107         (460 sq.m.) Plot Area
108         (251 sq.m.) Plot Area
109         (815 sq.m.) Plot Area
112         (301 sq.m.) Plot Area
113          (73 sq.m.) Plot Area
114          (25 sq.m.) Plot Area
116         (502 sq.m.) Plot Area
117         (220 sq.m.) Plot Area
118         (254 sq.m.) Plot Area
119         (297 sq.m.) Plot Area
120         (301 sq.m.) Plot Area
121         (100 sq.m.) Plot Area
122         (244 sq.m.) Plot Area
123         (134 sq.m.) Plot Area
124         (209 sq.m.) Plot Area
125         (134 sq.m.) Plot Area
126         (223 sq.m.) Plot Area
127         (372 sq.m.) Plot Area
128         (209 sq.m.) Plot Area
129         (418 sq.m.) Plot Area
130         (502 sq.m.) Plot Area
131         (334 sq.m.) Plot Area
132         (502 sq.m.) Plot Area
133         (226 sq.m.) Plot Area
134         (135 sq.m.) Plot Area
135         (161 sq.m.) Plot Area
136         (226 sq.m.) Plot Area
137         (206 sq.m.) Plot Area
138         (557 sq.m.) Plot Area
139     (557 sq.m.) Built-up Area
140         (167 sq.m.) Plot Area
141     (650 sq.m.) Built-up Area
142         (743 sq.m.) Plot Area
143          (67 sq.m.) Plot Area
144         (125 sq.m.) Plot Area
145        (1254 sq.m.) Plot Area
146           (6 sq.m.) Plot Area
147           (7 sq.m.) Plot Area
148           (6 sq.m.) Plot Area
149           (7 sq.m.) Plot Area
150         (180 sq.m.) Plot Area
151         (226 sq.m.) Plot Area
152        (2592 sq.m.) Plot Area
153         (140 sq.m.) Plot Area
154         (167 sq.m.) Plot Area
155         (145 sq.m.) Plot Area
156          (89 sq.m.) Plot Area
157         (180 sq.m.) Plot Area
158         (418 sq.m.) Plot Area
159         (201 sq.m.) Plot Area
160         (360 sq.m.) Plot Area
161         (418 sq.m.) Plot Area
162         (418 sq.m.) Plot Area
163     (511 sq.m.) Built-up Area
164         (502 sq.m.) Plot Area
165          (13 sq.m.) Plot Area
166          (51 sq.m.) Plot Area
167          (64 sq.m.) Plot Area
168          (50 sq.m.) Plot Area
169          (99 sq.m.) Plot Area
170         (293 sq.m.) Plot Area
171      (94 sq.m.) Built-up Area
172          (52 sq.m.) Plot Area
173          (84 sq.m.) Plot Area
174          (98 sq.m.) Plot Area
175         (230 sq.m.) Plot Area
176         (151 sq.m.) Plot Area
177         (140 sq.m.) Plot Area
178           (5 sq.m.) Plot Area
179          (84 sq.m.) Plot Area
180     (279 sq.m.) Built-up Area
181          (63 sq.m.) Plot Area
182          (56 sq.m.) Plot Area
183          (84 sq.m.) Plot Area
184      (42 sq.m.) Built-up Area
185           (7 sq.m.) Plot Area
186          (42 sq.m.) Plot Area
187        (46 sq.m.) Carpet Area
188          (91 sq.m.) Plot Area
189          (22 sq.m.) Plot Area
190         (167 sq.m.) Plot Area
191         (166 sq.m.) Plot Area
192         (334 sq.m.) Plot Area
193          (84 sq.m.) Plot Area
194      (10 sq.m.) Built-up Area
195         (158 sq.m.) Plot Area
196     (121 sq.m.) Built-up Area
197         (139 sq.m.) Plot Area
198      (42 sq.m.) Built-up Area
199         (125 sq.m.) Plot Area
200         (111 sq.m.) Plot Area
201          (63 sq.m.) Plot Area
202          (84 sq.m.) Plot Area
203         (167 sq.m.) Plot Area
204         (209 sq.m.) Plot Area
205         (261 sq.m.) Plot Area
206       (260 sq.m.) Carpet Area
207         (339 sq.m.) Plot Area
208        (92 sq.m.) Carpet Area
209     (104 sq.m.) Built-up Area
210      (63 sq.m.) Built-up Area
211          (25 sq.m.) Plot Area
212       (302 sq.m.) Carpet Area
213          (43 sq.m.) Plot Area
214         (209 sq.m.) Plot Area
215         (418 sq.m.) Plot Area
216         (253 sq.m.) Plot Area
217         (135 sq.m.) Plot Area
218         (107 sq.m.) Plot Area
219     (316 sq.m.) Built-up Area
220          (33 sq.m.) Plot Area
221       (301 sq.m.) Carpet Area
222         (125 sq.m.) Plot Area
223          (84 sq.m.) Plot Area
224          (33 sq.m.) Plot Area
225        (2415 sq.m.) Plot Area
226          (84 sq.m.) Plot Area
227         (125 sq.m.) Plot Area
228          (88 sq.m.) Plot Area
229         (166 sq.m.) Plot Area
230      (76 sq.m.) Built-up Area
231      (32 sq.m.) Built-up Area
232        (50 sq.m.) Carpet Area
233      (18 sq.m.) Built-up Area
234      (22 sq.m.) Built-up Area
235         (431 sq.m.) Plot Area
236         (121 sq.m.) Plot Area
237       (5 sq.m.) Built-up Area
238          (41 sq.m.) Plot Area
239     (200 sq.m.) Built-up Area
240      (93 sq.m.) Built-up Area
241      (42 sq.m.) Built-up Area
242          (52 sq.m.) Plot Area
243          (84 sq.m.) Plot Area
244     (279 sq.m.) Built-up Area
245         (171 sq.m.) Plot Area
246         (372 sq.m.) Plot Area
247         (301 sq.m.) Plot Area
248      (12 sq.m.) Built-up Area
249           (5 sq.m.) Plot Area
251     (325 sq.m.) Built-up Area
252         (201 sq.m.) Plot Area
253          (67 sq.m.) Plot Area
254        (28 sq.m.) Carpet Area
255      (20 sq.m.) Built-up Area
256      (44 sq.m.) Built-up Area
257          (84 sq.m.) Plot Area
258         (133 sq.m.) Plot Area
259       (167 sq.m.) Carpet Area
262     (278 sq.m.) Built-up Area
263     (139 sq.m.) Built-up Area
264         (153 sq.m.) Plot Area
265          (28 sq.m.) Plot Area
266       (134 sq.m.) Carpet Area
267       (121 sq.m.) Carpet Area
268     (367 sq.m.) Built-up Area
269         (209 sq.m.) Plot Area
270      (809371 sq.m.) Plot Area
271          (90 sq.m.) Plot Area
272          (19 sq.m.) Plot Area
274         (167 sq.m.) Plot Area
275         (160 sq.m.) Plot Area
276         (135 sq.m.) Plot Area
279     (111 sq.m.) Built-up Area
280          (92 sq.m.) Plot Area
281     (557 sq.m.) Built-up Area
282     (149 sq.m.) Built-up Area
283         (465 sq.m.) Plot Area
285         (326 sq.m.) Plot Area
286           (6 sq.m.) Plot Area
287      (31 sq.m.) Built-up Area
288     (452 sq.m.) Built-up Area
289         (385 sq.m.) Plot Area
297          (33 sq.m.) Plot Area
298      (92 sq.m.) Built-up Area
300         (177 sq.m.) Plot Area
301      (84 sq.m.) Built-up Area
302         (167 sq.m.) Plot Area
303      (74 sq.m.) Built-up Area
304          (34 sq.m.) Plot Area
305      (87 sq.m.) Built-up Area
306          (42 sq.m.) Plot Area
307     (144 sq.m.) Built-up Area
308         (325 sq.m.) Plot Area
309       (9 sq.m.) Built-up Area
310      (51 sq.m.) Built-up Area
311       (929 sq.m.) Carpet Area
312     (219 sq.m.) Built-up Area
313     (279 sq.m.) Built-up Area
314     (102 sq.m.) Built-up Area
315     (279 sq.m.) Built-up Area
316     (219 sq.m.) Built-up Area
317      (13 sq.m.) Built-up Area
322     (233 sq.m.) Built-up Area
323         (418 sq.m.) Plot Area
327          (54 sq.m.) Plot Area
328          (52 sq.m.) Plot Area
329        (75 sq.m.) Carpet Area
330          (42 sq.m.) Plot Area
331     (478 sq.m.) Built-up Area
332          (57 sq.m.) Plot Area
333          (34 sq.m.) Plot Area
334          (89 sq.m.) Plot Area
335         (132 sq.m.) Plot Area
336          (71 sq.m.) Plot Area
337         (100 sq.m.) Plot Area
338     (100 sq.m.) Built-up Area
339     (105 sq.m.) Built-up Area
340          (95 sq.m.) Plot Area
341        (84 sq.m.) Carpet Area
342          (51 sq.m.) Plot Area
343          (84 sq.m.) Plot Area
344     (158 sq.m.) Built-up Area
345     (340 sq.m.) Built-up Area
346         (232 sq.m.) Plot Area
347         (134 sq.m.) Plot Area
348     (650 sq.m.) Built-up Area
349         (226 sq.m.) Plot Area
350         (115 sq.m.) Plot Area
351         (146 sq.m.) Plot Area
352         (109 sq.m.) Plot Area
353          (24 sq.m.) Plot Area
354      (56 sq.m.) Built-up Area
356          (84 sq.m.) Plot Area
357         (167 sq.m.) Plot Area
358      (45 sq.m.) Built-up Area
359      (15 sq.m.) Built-up Area
360     (220 sq.m.) Built-up Area
361      (45 sq.m.) Built-up Area
362      (25 sq.m.) Built-up Area
363           (9 sq.m.) Plot Area
364        (56 sq.m.) Carpet Area
365     (102 sq.m.) Built-up Area
366           (5 sq.m.) Plot Area
367          (50 sq.m.) Plot Area
368      (33 sq.m.) Built-up Area
369          (84 sq.m.) Plot Area
370          (14 sq.m.) Plot Area
372       (251 sq.m.) Carpet Area
373         (301 sq.m.) Plot Area
374         (151 sq.m.) Plot Area
375          (33 sq.m.) Plot Area
376          (18 sq.m.) Plot Area
377        (75 sq.m.) Carpet Area
378          (93 sq.m.) Plot Area
379       (325 sq.m.) Carpet Area
380        (23 sq.m.) Carpet Area
381         (291 sq.m.) Plot Area
382          (84 sq.m.) Plot Area
383          (84 sq.m.) Plot Area
385         (226 sq.m.) Plot Area
386         (246 sq.m.) Plot Area
387         (435 sq.m.) Plot Area
388          (52 sq.m.) Plot Area
389         (460 sq.m.) Plot Area
390          (47 sq.m.) Plot Area
391          (50 sq.m.) Plot Area
392           (5 sq.m.) Plot Area
393          (85 sq.m.) Plot Area
394        (7692 sq.m.) Plot Area
395         (226 sq.m.) Plot Area
396          (33 sq.m.) Plot Area
397         (124 sq.m.) Plot Area
398          (84 sq.m.) Plot Area
399     (132 sq.m.) Built-up Area
400        (93 sq.m.) Carpet Area
401     (301 sq.m.) Built-up Area
402          (73 sq.m.) Plot Area
403          (59 sq.m.) Plot Area
404         (105 sq.m.) Plot Area
405           (7 sq.m.) Plot Area
406     (163 sq.m.) Built-up Area
407         (184 sq.m.) Plot Area
408     (105 sq.m.) Built-up Area
409          (52 sq.m.) Plot Area
410         (293 sq.m.) Plot Area
411          (49 sq.m.) Plot Area
412          (84 sq.m.) Plot Area
413         (113 sq.m.) Plot Area
414     (132 sq.m.) Built-up Area
415          (84 sq.m.) Plot Area
416        (84 sq.m.) Carpet Area
417         (167 sq.m.) Plot Area
418         (136 sq.m.) Plot Area
419          (33 sq.m.) Plot Area
420         (109 sq.m.) Plot Area
421        (40 sq.m.) Carpet Area
422     (483 sq.m.) Built-up Area
423          (42 sq.m.) Plot Area
424          (46 sq.m.) Plot Area
425          (50 sq.m.) Plot Area
426       (20064 sq.m.) Plot Area
427          (56 sq.m.) Plot Area
428      (15 sq.m.) Built-up Area
429          (14 sq.m.) Plot Area
430          (98 sq.m.) Plot Area
431     (328 sq.m.) Built-up Area
432         (336 sq.m.) Plot Area
433           (5 sq.m.) Plot Area
434         (167 sq.m.) Plot Area
435          (84 sq.m.) Plot Area
437         (110 sq.m.) Plot Area
438         (167 sq.m.) Plot Area
439       (151 sq.m.) Carpet Area
440          (56 sq.m.) Plot Area
441          (76 sq.m.) Plot Area
442          (15 sq.m.) Plot Area
443          (40 sq.m.) Plot Area
445       (234 sq.m.) Carpet Area
446          (43 sq.m.) Plot Area
448      (42 sq.m.) Built-up Area
449          (58 sq.m.) Plot Area
450          (28 sq.m.) Plot Area
451          (56 sq.m.) Plot Area
452          (65 sq.m.) Plot Area
453          (42 sq.m.) Plot Area
454         (372 sq.m.) Plot Area
455          (33 sq.m.) Plot Area
456         (125 sq.m.) Plot Area
457         (121 sq.m.) Plot Area
458         (117 sq.m.) Plot Area
459         (125 sq.m.) Plot Area
460          (84 sq.m.) Plot Area
461         (100 sq.m.) Plot Area
463          (50 sq.m.) Plot Area
464          (42 sq.m.) Plot Area
465         (113 sq.m.) Plot Area
466         (390 sq.m.) Plot Area
467         (167 sq.m.) Plot Area
468          (63 sq.m.) Plot Area
469          (84 sq.m.) Plot Area
470         (136 sq.m.) Plot Area
471          (74 sq.m.) Plot Area
472          (99 sq.m.) Plot Area
473          (42 sq.m.) Plot Area
474         (174 sq.m.) Plot Area
475      (6062 sq.m.) Carpet Area
476        (49 sq.m.) Carpet Area
477       (5 sq.m.) Built-up Area
478      (89 sq.m.) Built-up Area
479      (89 sq.m.) Built-up Area
480          (50 sq.m.) Plot Area
481          (42 sq.m.) Plot Area
482          (98 sq.m.) Plot Area
483      (52 sq.m.) Built-up Area
484     (188 sq.m.) Built-up Area
485         (5 sq.m.) Carpet Area
486       (301 sq.m.) Carpet Area
487     (117 sq.m.) Built-up Area
488        (46 sq.m.) Carpet Area
489     (251 sq.m.) Built-up Area
490     (149 sq.m.) Built-up Area
491     (139 sq.m.) Built-up Area
492     (125 sq.m.) Built-up Area
493        (84 sq.m.) Carpet Area
494      (98 sq.m.) Built-up Area
495     (251 sq.m.) Built-up Area
496     (135 sq.m.) Built-up Area
497     (418 sq.m.) Built-up Area
498     (301 sq.m.) Built-up Area
499     (242 sq.m.) Built-up Area
500       (291 sq.m.) Carpet Area
501     (207 sq.m.) Built-up Area
502     (124 sq.m.) Built-up Area
503     (167 sq.m.) Built-up Area
504         (204 sq.m.) Plot Area
505       (195 sq.m.) Carpet Area
506     (681 sq.m.) Built-up Area
507          (84 sq.m.) Plot Area
508          (51 sq.m.) Plot Area
509           (9 sq.m.) Plot Area
510         (161 sq.m.) Plot Area
511          (84 sq.m.) Plot Area
512          (33 sq.m.) Plot Area
513      (33 sq.m.) Built-up Area
514          (93 sq.m.) Plot Area
515          (83 sq.m.) Plot Area
516          (83 sq.m.) Plot Area
517          (42 sq.m.) Plot Area
518         (167 sq.m.) Plot Area
519       (111 sq.m.) Carpet Area
520     (372 sq.m.) Built-up Area
521          (84 sq.m.) Plot Area
523        (84 sq.m.) Carpet Area
524     (138 sq.m.) Built-up Area
525       (207 sq.m.) Carpet Area
526        (96 sq.m.) Carpet Area
527        (44 sq.m.) Carpet Area
528     (121 sq.m.) Built-up Area
529       (100 sq.m.) Carpet Area
530     (557 sq.m.) Built-up Area
531     (125 sq.m.) Built-up Area
532     (100 sq.m.) Built-up Area
533          (84 sq.m.) Plot Area
534     (339 sq.m.) Built-up Area
535     (437 sq.m.) Built-up Area
536     (167 sq.m.) Built-up Area
537     (418 sq.m.) Built-up Area
538      (84 sq.m.) Built-up Area
539     (162 sq.m.) Built-up Area
540     (248 sq.m.) Built-up Area
541      (93 sq.m.) Built-up Area
542       (107 sq.m.) Carpet Area
543      (46 sq.m.) Built-up Area
544        (84 sq.m.) Carpet Area
545      (70 sq.m.) Built-up Area
546       (102 sq.m.) Carpet Area
547         (264 sq.m.) Plot Area
549         (139 sq.m.) Plot Area
550         (281 sq.m.) Plot Area
551       (186 sq.m.) Carpet Area
552          (67 sq.m.) Plot Area
553         (251 sq.m.) Plot Area
554         (115 sq.m.) Plot Area
555     (201 sq.m.) Built-up Area
556     (111 sq.m.) Built-up Area
557      (93 sq.m.) Built-up Area
558         (152 sq.m.) Plot Area
559     (353 sq.m.) Built-up Area
560      (46 sq.m.) Built-up Area
561          (66 sq.m.) Plot Area
562      (70 sq.m.) Built-up Area
563          (80 sq.m.) Plot Area
564         (836 sq.m.) Plot Area
565          (79 sq.m.) Plot Area
566         (107 sq.m.) Plot Area
567     (176 sq.m.) Built-up Area
568          (37 sq.m.) Plot Area
569           (5 sq.m.) Plot Area
570     (100 sq.m.) Built-up Area
571     (209 sq.m.) Built-up Area
572         (125 sq.m.) Plot Area
573     (143 sq.m.) Built-up Area
574          (84 sq.m.) Plot Area
575          (69 sq.m.) Plot Area
576        (73 sq.m.) Carpet Area
577          (88 sq.m.) Plot Area
578         (125 sq.m.) Plot Area
579          (46 sq.m.) Plot Area
580         (354 sq.m.) Plot Area
581     (594 sq.m.) Built-up Area
582      (76 sq.m.) Built-up Area
583     (209 sq.m.) Built-up Area
585          (50 sq.m.) Plot Area
586     (222 sq.m.) Built-up Area
587         (130 sq.m.) Plot Area
588      (93 sq.m.) Built-up Area
589          (56 sq.m.) Plot Area
590          (60 sq.m.) Plot Area
591      (84 sq.m.) Built-up Area
592          (44 sq.m.) Plot Area
593      (71 sq.m.) Built-up Area
594           (9 sq.m.) Plot Area
595     (102 sq.m.) Built-up Area
596     (249 sq.m.) Built-up Area
597     (186 sq.m.) Built-up Area
598      (42 sq.m.) Built-up Area
599     (186 sq.m.) Built-up Area
600          (42 sq.m.) Plot Area
601     (153 sq.m.) Built-up Area
602           (6 sq.m.) Plot Area
603          (50 sq.m.) Plot Area
604          (51 sq.m.) Plot Area
605          (84 sq.m.) Plot Area
606          (59 sq.m.) Plot Area
607          (91 sq.m.) Plot Area
608          (51 sq.m.) Plot Area
609         (100 sq.m.) Plot Area
610     (125 sq.m.) Built-up Area
611         (151 sq.m.) Plot Area
612           (4 sq.m.) Plot Area
613         (217 sq.m.) Plot Area
614          (84 sq.m.) Plot Area
615         (184 sq.m.) Plot Area
616         (420 sq.m.) Plot Area
617         (100 sq.m.) Plot Area
618      (75 sq.m.) Built-up Area
619         (401 sq.m.) Plot Area
620          (50 sq.m.) Plot Area
622         (108 sq.m.) Plot Area
623          (54 sq.m.) Plot Area
624         (209 sq.m.) Plot Area
625         (286 sq.m.) Plot Area
626          (50 sq.m.) Plot Area
627          (50 sq.m.) Plot Area
628         (251 sq.m.) Plot Area
629          (84 sq.m.) Plot Area
630          (84 sq.m.) Plot Area
631          (93 sq.m.) Plot Area
632         (318 sq.m.) Plot Area
633        (1003 sq.m.) Plot Area
634         (100 sq.m.) Plot Area
635          (21 sq.m.) Plot Area
636          (93 sq.m.) Plot Area
637          (99 sq.m.) Plot Area
638         (213 sq.m.) Plot Area
639         (502 sq.m.) Plot Area
640          (44 sq.m.) Plot Area
641         (109 sq.m.) Plot Area
642         (105 sq.m.) Plot Area
643         (420 sq.m.) Plot Area
644         (125 sq.m.) Plot Area
645     (650 sq.m.) Built-up Area
646         (420 sq.m.) Plot Area
647         (264 sq.m.) Plot Area
648         (420 sq.m.) Plot Area
649         (301 sq.m.) Plot Area
650         (251 sq.m.) Plot Area
651         (420 sq.m.) Plot Area
652         (145 sq.m.) Plot Area
653         (420 sq.m.) Plot Area
654         (301 sq.m.) Plot Area
655          (37 sq.m.) Plot Area
656          (84 sq.m.) Plot Area
657          (84 sq.m.) Plot Area
658     (590 sq.m.) Built-up Area
659         (196 sq.m.) Plot Area
660          (50 sq.m.) Plot Area
661         (418 sq.m.) Plot Area

In [20]:
df['area'] = df['area'].str.split(')').str.get(0).str.split(' ').str.get(0).str.replace('(', '').astype(int)

In [21]:
df['area']  = df['area'].apply(lambda x : x * 10.76)

In [22]:
df.head()

,property_name,society,price,rate,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25,"₹ 20,115/sq.ft.",2603.92,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.70,"₹ 105,751/sq.ft.",538.00,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.10,"₹ 38,251/sq.ft.",548.76,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5.00,"₹ 43,066/sq.ft.",1162.08,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3.00,"₹ 53,763/sq.ft.",559.52,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [23]:
df.rename(columns={'rate':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25,"₹ 20,115/sq.ft.",2603.92,Plot area 290(242.48 sq.m.),5 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.70,"₹ 105,751/sq.ft.",538.00,Plot area 539(50.07 sq.m.),5 Bedrooms,4 Bathrooms,2 Balconies,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.10,"₹ 38,251/sq.ft.",548.76,Plot area 61(51 sq.m.),10 Bedrooms,10 Bathrooms,3+ Balconies,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5.00,"₹ 43,066/sq.ft.",1162.08,Plot area 129(107.86 sq.m.),21 Bedrooms,21 Bathrooms,3+ Balconies,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3.00,"₹ 53,763/sq.ft.",559.52,Plot area 62(51.84 sq.m.),12 Bedrooms,12 Bathrooms,3+ Balconies,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [24]:
df['bedRoom'].isnull().sum()

0

In [25]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype(int)

In [26]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype(int)

In [27]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('+', '').str.replace('No', '0').astype(int)

In [28]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,noOfFloor,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,Bptp Visionnaire,5.25,"₹ 20,115/sq.ft.",2603.92,Plot area 290(242.48 sq.m.),5,4,3,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3 Floors,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.70,"₹ 105,751/sq.ft.",538.00,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2 Floors,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.10,"₹ 38,251/sq.ft.",548.76,Plot area 61(51 sq.m.),10,10,3,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5.00,"₹ 43,066/sq.ft.",1162.08,Plot area 129(107.86 sq.m.),21,21,3,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5 Floors,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3.00,"₹ 53,763/sq.ft.",559.52,Plot area 62(51.84 sq.m.),12,12,3,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5 Floors,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 958 entries, 0 to 1043
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    958 non-null    object
 1   society          391 non-null    object
 2   price            958 non-null    float64
 3   price_per_sqft   958 non-null    object
 4   area             958 non-null    float64
 5   areaWithType     958 non-null    object
 6   bedRoom          958 non-null    int32
 7   bathroom         958 non-null    int32
 8   balcony          958 non-null    int32
 9   additionalRoom   577 non-null    object
 10  address          953 non-null    object
 11  noOfFloor        938 non-null    object
 12  facing           660 non-null    object
 13  agePossession    958 non-null    object
 14  nearbyLocations  843 non-null    object
 15  description      958 non-null    object
 16  furnishDetails   726 non-null    object
 17  features         659 non-null    object
dtypes: float64(2), int32(3), object(13)
memory usage: 131.0+ KB

In [30]:
df['noOfFloor'] = df['noOfFloor'].str.split(' ').str.get(0).str.replace('Ground', '0').str.replace('Basement', '0').str.replace('Lower', '0').str.extract(r'(\d+)').astype(float)

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 958 entries, 0 to 1043
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    958 non-null    object
 1   society          391 non-null    object
 2   price            958 non-null    float64
 3   price_per_sqft   958 non-null    object
 4   area             958 non-null    float64
 5   areaWithType     958 non-null    object
 6   bedRoom          958 non-null    int32
 7   bathroom         958 non-null    int32
 8   balcony          958 non-null    int32
 9   additionalRoom   577 non-null    object
 10  address          953 non-null    object
 11  noOfFloor        938 non-null    float64
 12  facing           660 non-null    object
 13  agePossession    958 non-null    object
 14  nearbyLocations  843 non-null    object
 15  description      958 non-null    object
 16  furnishDetails   726 non-null    object
 17  features         659 non-null    object
dtypes: float64(3), int32(3), object(12)
memory usage: 131.0+ KB

In [32]:
df['society'] = (
    df['society']
    .str.replace(r'\d+(\.\d+)?\s?★', '', regex=True)
    .str.strip()
    .str.lower())
df['society'].value_counts().shape

(177,)

In [33]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.split(' ').str.get(1).str.replace(',', '').astype(int)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 958 entries, 0 to 1043
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    958 non-null    object
 1   society          391 non-null    object
 2   price            958 non-null    float64
 3   price_per_sqft   958 non-null    int32
 4   area             958 non-null    float64
 5   areaWithType     958 non-null    object
 6   bedRoom          958 non-null    int32
 7   bathroom         958 non-null    int32
 8   balcony          958 non-null    int32
 9   additionalRoom   577 non-null    object
 10  address          953 non-null    object
 11  noOfFloor        938 non-null    float64
 12  facing           660 non-null    object
 13  agePossession    958 non-null    object
 14  nearbyLocations  843 non-null    object
 15  description      958 non-null    object
 16  furnishDetails   726 non-null    object
 17  features         659 non-null    object
dtypes: float64(3), int32(4), object(11)
memory usage: 127.2+ KB

In [35]:
df.rename(columns={'noOfFloor':'floorNum'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115,2603.92,Plot area 290(242.48 sq.m.),5,4,3,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.70,105751,538.00,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.10,38251,548.76,Plot area 61(51 sq.m.),10,10,3,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5.00,43066,1162.08,Plot area 129(107.86 sq.m.),21,21,3,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5.0,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3.00,53763,559.52,Plot area 62(51.84 sq.m.),12,12,3,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 958 entries, 0 to 1043
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    958 non-null    object
 1   society          391 non-null    object
 2   price            958 non-null    float64
 3   price_per_sqft   958 non-null    int32
 4   area             958 non-null    float64
 5   areaWithType     958 non-null    object
 6   bedRoom          958 non-null    int32
 7   bathroom         958 non-null    int32
 8   balcony          958 non-null    int32
 9   additionalRoom   577 non-null    object
 10  address          953 non-null    object
 11  floorNum         938 non-null    float64
 12  facing           660 non-null    object
 13  agePossession    958 non-null    object
 14  nearbyLocations  843 non-null    object
 15  description      958 non-null    object
 16  furnishDetails   726 non-null    object
 17  features         659 non-null    object
dtypes: float64(3), int32(4), object(11)
memory usage: 127.2+ KB

In [37]:
df['facing'].fillna('DK', inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10976\1838074268.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('DK', inplace=True)

In [39]:
df.head()

,property_name,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
0,5 Bedroom House for sale in Sector 70A Gurgaon,bptp visionnaire,5.25,20115,2603.92,Plot area 290(242.48 sq.m.),5,4,3,Servant Room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
1,5 Bedroom House for sale in Sector 21A Faridabad,NaN,5.70,105751,538.00,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2.0,DK,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
2,10 Bedroom House for sale in Sushant Lok Phase 1,NaN,2.10,38251,548.76,Plot area 61(51 sq.m.),10,10,3,Servant Room,"Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,NaN,5.00,43066,1162.08,Plot area 129(107.86 sq.m.),21,21,3,Servant Room,"Sector 54 Gurgaon, Gurgaon, Haryana",5.0,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,NaN,3.00,53763,559.52,Plot area 62(51.84 sq.m.),12,12,3,Others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito..."

In [40]:
df.insert(loc=1, column='type', value='house')

In [42]:
df.sample(10)

,property_name,type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
772,12 Bedroom House for sale in Mehrauli Gurgaon ...,house,NaN,8.00,17707,4519.20,Plot area 502(419.74 sq.m.),12,4,3,"Servant Room,Store Room","Mehrauli Gurgaon Road, Gurgaon, Haryana",3.0,North,10+ Year Old,"['Mg road metro station', 'Iffco chowk metro s...",Its north and park facing. Main iffco chowk wa...,"['1 Wardrobe', '1 Fan', '5 Light', '1 AC', 'No...","['High Ceiling Height', 'Water Storage', 'No o..."
258,10 Bedroom House for sale in Ravi Nagar,house,NaN,1.25,8735,1431.08,Plot area 159(132.94 sq.m.),10,6,3,NaN,"Ravi Nagar, Gurgaon, Haryana",3.0,DK,10+ Year Old,"['State bank ATM', 'Ankur Clinic and Maternity...",It is a 159 gaj two side open plot with 5 two ...,[],NaN
1,5 Bedroom House for sale in Sector 21A Faridabad,house,NaN,5.70,105751,538.00,Plot area 539(50.07 sq.m.),5,4,2,"Store Room,Pooja Room,Servant Room","Sector 21A Faridabad, Gurgaon, Haryana",2.0,DK,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ..."
175,7 Bedroom House for sale in South City 1,house,NaN,7.00,28283,2474.80,Plot area 275(229.94 sq.m.),7,7,3,"Pooja Room,Study Room,Servant Room,Store Room","South City 1, Gurgaon, Haryana",3.0,South-West,5 to 10 Year Old,"['Huda city centre metro station', 'Axis bank ...","275 sq yard kothi , park facing , m block sout...","['1 Water Purifier', '10 Fan', '1 Fridge', '1 ...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
826,4 Bedroom House for sale in Sector 86 Gurgaon,house,dlf new town heights,2.50,7827,3195.72,Plot area 3194(296.73 sq.m.),4,5,3,"Pooja Room,Servant Room,Others","Th98, Sector 86 Gurgaon, Gurgaon, Haryana",4.0,West,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...",Society is very beautiful around of trees gard...,"['7 Fan', '1 Exhaust Fan', '3 Geyser', '10 Lig...","['Feng Shui / Vaastu Compliant', 'Private Gard..."
476,2 Bedroom House for sale in Palam Vihar Extension,house,NaN,0.40,7619,527.24,Carpet area: 525 (48.77 sq.m.),2,2,1,NaN,"Palam Vihar Extension, Palam Vihar Extension, ...",1.0,DK,1 to 5 Year Old,NaN,Best in class property available at palam viha...,"['1 Fan', '1 Light', '1 Wardrobe', 'No AC', 'N...",NaN
468,5 Bedroom House for sale in Laxman Vihar,house,NaN,0.80,11852,677.88,Plot area 75(62.71 sq.m.),5,3,1,NaN,"Laxman Vihar, Gurgaon, Haryana",2.0,DK,5 to 10 Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...",Interested to sell independent house/villa.Pla...,"['5 Fan', '15 Light', 'No AC', 'No Bed', 'No C...",NaN
1005,2 Bedroom House for sale in Jyoti Park,house,NaN,1.00,79365,129.12,Plot area 126(11.71 sq.m.),2,2,0,Study Room,"101, Jyoti Park, Gurgaon, Haryana",0.0,DK,10+ Year Old,"['State bank ATM', 'Dr. Madan Clinic', 'Taneja...",Near to school market mall hospital,"['1 Fan', '1 Light', '1 Modular Kitchen', 'No ...","['Water Storage', 'Waste Disposal']"
136,4 Bedroom House for sale in Sector 109 Gurgaon,house,international city by sobha phase 1,5.90,24280,2431.76,Plot area 270(225.75 sq.m.),4,5,2,Servant Room,"N/a, Sector 109 Gurgaon, Gurgaon, Haryana",2.0,East,1 to 5 Year Old,"['Dwarka sector 21 metro station', 'Pacific D2...",Nice villa in dwarka express way and good loca...,"['5 Fan', '1 Exhaust Fan', '2 Geyser', '1 Stov...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
781,4 Bedroom House for sale in Sector 48 Gurgaon,house,vipul tatvam villa,8.40,21000,4002.72,Plot area 4000(371.61 sq.m.),4,5,3,"Pooja Room,Study Room,Servant Room","Sector 48 Gurgaon, Gurgaon, Haryana",2.0,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Wishing to settle down in an individual house ...,"['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard..."

In [43]:
df.society.value_counts()

society
vipul tatvam villa                                   21
international city by sobha phase 2                  19
international city by sobha phase 1                  15
emaar mgf marbella                                   13
dlf city plots phase 2                               11
dlf city plots                                       11
unitech uniworld resorts                             10
unitech espace                                       10
bptp visionnaire                                      9
uppal southend                                        8
not applicable                                        6
eldeco mansionz                                       6
dlf new town heights                                  6
ansals palam vihar                                    6
sushant lok 1 builder floors                          6
dlf city phase 1                                      5
nul                                                   4
vatika india next                                     4
experion windchants                                   4
unitech aspen greens                                  4
ansal sushant lok plots                               4
eros rosewood city                                    3
palam vihar extension west zone rwa                   3
rattan garden                                         3
luxury dlf city floors                                3
ss aaron ville                                        3
housing board colony                                  3
vatika signature villas                               3
dlf city plots phase 3                                3
eros rosewood villas                                  3
ansals florence villa                                 3
bptp astaire gardens                                  3
unitech nirvana birch court                           3
sector 14 rwa                                         3
malibu towne                                          3
sector 38 rwa                                         2
unitech escape                                        2
iffco nagar and 17b rwa                               2
bhim garh kheri                                       2
unitech palms south city 1                            2
ardee city                                            2
bptp pedestal                                         2
ireo victory valley                                   2
rwa sector 46                                         2
nirvana cedar crest                                   2
satya the hermitage                                   2
tata primanti                                         2
suncity township                                      2
ss hibiscus                                           2
nirvana country                                       2
emaar the palm springs                                2
hans enclave                                          2
silverglades tarudhan valley golf resort              2
suncity essel towers                                  2
unitech deerwood chase                                2
spaze privy                                           2
project housing board colony                          2
project mianwali colony                               2
ansal api esencia                                     2
shivpuri                                              2
ansal api spanish court                               1
central park flower valley cerise floors              1
farrukhnagar                                          1
emaar emerald hills                                   1
dlf garden city floors                                1
4s aradhya homes                                      1
ashok vihar phase 3 gurgaon                           1
prem kunj                                             1
ansal florence super                                  1
smart world orchard                                   1
unitech south city                                    1
huda ashok vihar phase                                1
birla navya                                           1
secter 16a daultabad faridabad house no 313           1
dlf floors phase 3                                    1
kothi                                                 1
rajendra park sec 105                                 1
dlf city plots phase 4                                1
ansal heights                                         1
landmark house                                        1
ninex city                                            1
cloudnine cottages                                    1
u block dlf phase 3 road no 21                        1
sector 15 part 2 rwa                                  1
nitin vihar                                           1
ansal                                                 1
private house                                         1
dlf south city 1                                      1
ansal sushant residency                               1
sector-17c                                            1
huda floor                                            1
huda                                                  1
grover homes sec 4                                    1
sector 57 huda                                        1
saksham welfare association                           1
godrej meridien                                       1
ansal sushant lok 2                                   1
the laburnum                                          1
vatika independent floors                             1
arjun marg/ sector- 26 phase- 1/ golf course road     1
central park flower valley                            1
dlf pink town house                                   1
floor wise designer kothi                             1
satya the legend                                      1
sector 37                                             1
bestech park view ananda                              1
independent house sector 45                           1
dlf alameda                                           1
puri diplomatic greens                                1
huda sector-56 gurgaon                                1
vatika the seven lamps                                1
ansal sushant lok                                     1
central park                                          1
signature global city 81                              1
signature global city                                 1
ashok vihar phase iii extension                       1
rattan vihar rajendra park                            1
huda plots                                            1
signature global city 63a                             1
madan puri                                            1
ats tourmaline                                        1
row house                                             1
huda plot sector 38                                   1
bhawani enclave                                       1
mian wali                                             1
shri shyam residency                                  1
ansal celebrity homes                                 1
laxmi garden sector-11                                1
huda housing board colony                             1
tulip yellow                                          1
shree krishna homes                                   1
smart world gems                                      1
ganpati heights apartment                             1
hero homes                                            1
jacobpura gurugram                                    1
anant raj estates                                     1
anand garden, sector-105                              1
rk excelo                                             1
dlf the grove                                         1
surendra homes dayanand colony                        1
om nagar, sector-11                                   1
vatika sovereign next                                 1
manohar nagar                                         1
anamika enclave                                       1
bhim nagar, sector 6                                  1
dlf the arbour                                        1
indiabulls centrum park                               1
jacobpura                                             1
huda flats                                            1
nirmal enclave, maruti kunj road                      1
adani brahma samsara                                  1
sneh vihar                                            1
sheetla enclave                                       1
suncity avenue 76                                     1
ss omnia                                              1
signature global park                                 1
anshul                                                1
sare crescent parc royal greens phase 1               1
my home                                               1
vipul world                                           1
greenopolis                                           1
ansal esencia sovereign floors                        1
jacob pura                                            1
house number b-34                                     1
mahavir pura                                          1
sobha city                                            1
raj villas                                            1
surat nagar phase 2                                   1
shivaji nagar residential                             1
bhim nagar society                                    1
dlf gardencity enclave                                1
signature global city 92                              1
dlf city plot phase 4                                 1
sai kripa floors 5                                    1
naman residency                                       1
rajendra park gurgaon                                 1
krishna palace                                        1
Name: count, dtype: int64

In [44]:
df.isnull().sum()

property_name        0
type                 0
society            567
price                0
price_per_sqft       0
area                 0
areaWithType         0
bedRoom              0
bathroom             0
balcony              0
additionalRoom     381
address              5
floorNum            20
facing               0
agePossession        0
nearbyLocations    115
description          0
furnishDetails     232
features           299
dtype: int64