In [53]:
import pandas as pd 
import numpy as np

In [54]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [55]:
df = pd.read_csv('data_merged.csv')

In [56]:
df.sample(5)

,property_name,type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
1201,3 BHK Flat in Sector 104 Gurgaon,flat,godrej summit,1.16,6387.0,1816.0,Carpet area: 1816 (168.71 sq.m.),3,4,3,Servant Room,"Sector 104 Gurgaon, Gurgaon, Haryana",8.0,East,1 to 5 Year Old,"['MG Road Metro Station', 'The Esplanade Mall'...",Good furnished flat having 3bhk servant room a...,"['2 Wardrobe', '5 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
1820,3 BHK Flat in Sector 69 Gurgaon,flat,tulip leaf,2.07,11423.0,1812.0,Super Built up area 1812(168.34 sq.m.),3,3,3,NaN,"Sector 69 Gurgaon, Gurgaon, Haryana",16.0,South-West,1 to 5 Year Old,"['Omaxe City Centre Sector 49', 'Southern Peri...",Looking for a 3 bhk property for sale in gurga...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Feng Shui / Vaastu Compliant', 'Security / F..."
1732,4 BHK Flat in Sector 54 Gurgaon,flat,dlf the belaire,7.00,23333.0,3000.0,Super Built up area 3000(278.71 sq.m.),4,6,3,"Servant Room,Pooja Room,Store Room","1259, Sector 54 Gurgaon, Gurgaon, Haryana",12.0,East,5 to 10 Year Old,"['Sector 42-43 Metro station', 'Horizon 1 Mall...","Situated in sector 54 gurgaon, dlf the belaire...","['6 Wardrobe', '7 Fan', '1 Exhaust Fan', '10 L...","['Security / Fire Alarm', 'Power Back-up', 'Fe..."
2156,3 BHK Flat in Nirvana Country,flat,the close north,2.50,11944.0,2093.0,Super Built up area 2093(194.45 sq.m.),3,3,3,Pooja Room,"111, Nirvana Country, Gurgaon, Haryana",11.0,North-East,1 to 5 Year Old,"['Sector 55-56 Metro Station', 'Eros City Squa...","3 bhk apartment for sale in the close north, a...","['3 Wardrobe', '1 Water Purifier', '5 Fan', '1...","['Water purifier', 'Power Back-up', 'Feng Shui..."
2800,3 BHK Flat in Sector 48 Gurgaon,flat,central park resorts,5.15,20900.0,2464.0,Super Built up area 2464(228.91 sq.m.)Built Up...,3,3,3,Servant Room,"10d, Sector 48 Gurgaon, Gurgaon, Haryana",8.0,North-West,5 to 10 Year Old,"['Huda Metro Station', 'Omaxe Celebration Mall...",This beautiful 3 bhk flat in sector 48 gurgaon...,"['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...","['Power Back-up', 'Intercom Facility', 'Lift(s..."

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3954 entries, 0 to 3953
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3954 non-null   object
 1   type             3954 non-null   object
 2   society          3386 non-null   object
 3   price            3954 non-null   float64
 4   price_per_sqft   3954 non-null   float64
 5   area             3954 non-null   float64
 6   areaWithType     3954 non-null   object
 7   bedRoom          3954 non-null   int64
 8   bathroom         3954 non-null   int64
 9   balcony          3954 non-null   int64
 10  additionalRoom   2269 non-null   object
 11  address          3943 non-null   object
 12  floorNum         3932 non-null   float64
 13  facing           3954 non-null   object
 14  agePossession    3953 non-null   object
 15  nearbyLocations  3748 non-null   object
 16  description      3954 non-null   object
 17  furnishDetails   2926 non-null   object
 18  features         3248 non-null   object
dtypes: float64(4), int64(3), object(12)
memory usage: 587.1+ KB

In [58]:
df.duplicated().sum()

137

In [59]:
df.drop_duplicates(inplace=True)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3817 entries, 0 to 3952
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3817 non-null   object
 1   type             3817 non-null   object
 2   society          3254 non-null   object
 3   price            3817 non-null   float64
 4   price_per_sqft   3817 non-null   float64
 5   area             3817 non-null   float64
 6   areaWithType     3817 non-null   object
 7   bedRoom          3817 non-null   int64
 8   bathroom         3817 non-null   int64
 9   balcony          3817 non-null   int64
 10  additionalRoom   2208 non-null   object
 11  address          3806 non-null   object
 12  floorNum         3796 non-null   float64
 13  facing           3817 non-null   object
 14  agePossession    3816 non-null   object
 15  nearbyLocations  3618 non-null   object
 16  description      3817 non-null   object
 17  furnishDetails   2826 non-null   object
 18  features         3150 non-null   object
dtypes: float64(4), int64(3), object(12)
memory usage: 596.4+ KB

In [61]:
df.isnull().sum()

property_name         0
type                  0
society             563
price                 0
price_per_sqft        0
area                  0
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom     1609
address              11
floorNum             21
facing                0
agePossession         1
nearbyLocations     199
description           0
furnishDetails      991
features            667
dtype: int64

In [62]:
import re

In [63]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [64]:
df['sector'] = df['sector'].str.lower()

In [65]:
df['sector'].isnull().sum()

0

In [66]:
df.sector.value_counts()

sector
sohna                                                        154
sector 85                                                    108
sector 102                                                   107
sector 92                                                     99
sector 69                                                     93
sector 90                                                     88
sector 65                                                     87
sector 81                                                     87
sector 109                                                    86
sector 79                                                     76
sector 83                                                     68
sector 86                                                     64
sector 37d                                                    63
sector 104                                                    63
sector 107                                                    60
sector 108                                                    58
sector 56                                                     56
sector 48                                                     55
sector 95                                                     54
sector 70a                                                    54
nirvana country                                               51
sector 37c                                                    51
sector-33 sohna                                               50
sector 70                                                     50
palam vihar                                                   49
sector 84                                                     49
sector 89                                                     49
sector 67                                                     47
sector 113                                                    43
dlf phase 1                                                   43
sector 61                                                     42
sector 103                                                    42
sector 66                                                     42
sector 82                                                     41
dlf phase 2                                                   40
sector 106                                                    38
sector 49                                                     36
sushant lok phase 1                                           30
sector 99a                                                    30
sector 68                                                     30
sector 72                                                     29
sector 71                                                     27
sector 77                                                     27
laxman vihar                                                  26
sector 54                                                     26
dlf phase 4                                                   24
sector 112                                                    23
sector 88a                                                    22
sector 111                                                    22
sector 67a                                                    21
dlf phase 3                                                   21
sector 22                                                     20
sector 33                                                     19
sector 82a                                                    19
sector 74                                                     18
sector 91                                                     17
sector 78                                                     17
sector 62                                                     16
sushant lok phase 3                                           16
sector 60                                                     15
sector 63a                                                    15
sector 110                                                    15
sector 1 imt manesar                                          14
sector 53                                                     14
sector 63                                                     14
sector 76                                                     14
sector 52                                                     14
gwal pahari                                                   14
sector 3                                                      14
rajendra park                                                 14
sector 14                                                     14
laxman vihar phase 2                                          13
dlf phase 5                                                   13
sector 46                                                     13
uppals southend                                               12
sector 50                                                     12
sohna road                                                    12
sector 38                                                     12
sector 99                                                     12
sector 36a                                                    12
sector 31                                                     12
sector 39                                                     11
ashok vihar phase 3 extension                                 11
sector 7                                                      10
sector 47                                                     10
sector 9a                                                     10
sector 1a imt manesar                                         10
sector 93                                                      9
sector 4                                                       9
south city 1                                                   9
sector 40                                                      8
palam vihar extension                                          8
c block sushant lok phase 1                                    8
malibu town                                                    8
ashok vihar phase 2                                            8
sector 43                                                      8
sector 57                                                      8
sector 89 a                                                    8
sector 95a                                                     8
sector 59                                                      8
sector 55                                                      8
dwarka expressway                                              8
sector 10a                                                     7
sector 26                                                      7
sector 51                                                      7
new colony                                                     7
sector 58                                                      7
mianwali colony                                                7
sector 36 sohna                                                7
ashok vihar                                                    6
jyoti park                                                     6
sector 1                                                       6
sector 11                                                      6
jacobpura                                                      6
rajiv nagar                                                    6
surat nagar 1                                                  6
sector 5                                                       6
sector 80                                                      5
sector 23a                                                     5
sector 105                                                     5
dayanand colony                                                5
sector 9                                                       5
subhash nagar                                                  5
arjun nagar                                                    5
greenwood city                                                 5
new palam vihar                                                5
ansal plaza                                                    5
mehrauli  road                                                 5
sector 2                                                       5
manesar                                                        5
sushant lok phase 2                                            5
sector 30                                                      5
saraswati vihar                                                5
bhondsi                                                        4
baldev nagar                                                   4
sector 36                                                      4
sector 3a                                                      4
adarsh nagar                                                   4
shivpuri                                                       4
dharam colony                                                  4
sector 28                                                      4
surya vihar                                                    4
ravi nagar                                                     4
sector 17                                                      4
imt manesar                                                    4
garhi harsaru                                                  4
devilal colony                                                 4
sector 6                                                       4
valley view estate                                             4
madanpuri                                                      4
shivaji nagar                                                  4
bhim nagar                                                     4
suncity                                                        4
krishna colony                                                 4
vishnu garden                                                  4
chakkarpur                                                     4
sector 12a                                                     4
new                                                            4
sector 17b                                                     3
sector 12                                                      3
sector 23                                                      3
gandhi nagar                                                   3
sector 73                                                      3
sector 8                                                       3
sector 110 a                                                   3
b block sushant lok phase 1                                    3
prem nagar                                                     3
a block sushant lok phase 1                                    3
sector 27                                                      3
sector 15                                                      3
laxmi garden                                                   3
sector 88b                                                     3
patel nagar                                                    3
sector 17a                                                     3
mg road                                                        3
sector 45                                                      3
maruti kunj                                                    3
rosewood                                                       2
surat nagar                                                    2
sector 15 part 2                                               2
new basti                                                      2
sushant lok                                                    2
hira nagar                                                     2
sector 41                                                      2
faridabad road                                                 2
rajiv chowk                                                    2
nars                                                           2
ambience island                                                2
sheetla colony                                                 2
farukhnagar                                                    2
mohan nagar                                                    2
surat nagar phase 2                                            2
manohar nagar                                                  2
sector-2 sohna                                                 2
block a surya vihar                                            2
golf course road                                               2
shakti nagar                                                   2
daulatabad                                                     2
new palam vihar phase 2                                        2
sector-11 sohna                                                2
sector 32                                                      2
shanti nagar                                                   2
pratap nagar                                                   2
sohna  road                                                    2
golf course ext road                                           2
, delhi ncr                                                    2
new palam vihar phase 1                                        2
iffco chowk                                                    2
sector 15 part 1                                               2
mayfield garden                                                2
sector 21                                                      2
acharya puri                                                   2
west rajiv nagar                                               2
bhawani enclave                                                2
bissar                                                         2
lajpat nagar                                                   2
old delhi road, opp sector-14                                  1
begampur khatola                                               1
tekchand nagar                                                 1
v block dlf phase 3                                            1
nirvana country pocket h                                       1
new jyoti park                                                 1
sector 5 chowk                                                 1
garauli kalan                                                  1
bptp                                                           1
sultanpur                                                      1
near nand hospital                                             1
new colony, sector 7                                           1
laxmna vihar, phase 2                                          1
kanahi                                                         1
hsiidc plot sector 1 imt manesar                               1
mahalaxmi garden, rajendra place                               1
huda saraswati vihar                                           1
civil l                                                        1
sector-35 sohna                                                1
sector 21a faridabad                                           1
near sector 1 market                                           1
ram nagar                                                      1
ansal's palam vihar                                            1
sector-5 sheetla colony                                        1
park view                                                      1
part 3 sector 5                                                1
ravi nager basai road                                          1
sec 3 bhim vihar part 1 bhimgher kheri                         1
damdma                                                         1
urban estate, sector 5                                         1
rajiv colony                                                   1
ashok vihar phase 3                                            1
sector 37a                                                     1
sector 4 urban estate                                          1
saraswati enclave                                              1
vir nagar                                                      1
laxman vihar, railway road,                                    1
bhimgarh kheri phase 3                                         1
devi lal colony gali no 12 gurgaon nr omkar public school      1
mahavir pura                                                   1
sector 13                                                      1
dhankot                                                        1
b1 block sector 57                                             1
g block dlf city phase 1                                       1
sector-5 sohna                                                 1
sector 37b                                                     1
bhora kalan                                                    1
ashok vihar phase i                                            1
sispal vihar                                                   1
hno 13 sagar enclave sura                                      1
sector 24                                                      1
rattan garden                                                  1
jacobpura near sadar bazar                                     1
lucknow                                                        1
samaspur                                                       1
block h ashok vihar phase iii extension                        1
ats marigold                                                   1
block g sector-57                                              1
cyber city                                                     1
pataudi road                                                   1
sector 42                                                      1
kheri                                                          1
alipur                                                         1
sector 9b                                                      1
sai kunj                                                       1
sadar bazar                                                    1
khandsa                                                        1
sector 17c                                                     1
carterpuri village                                             1
om nagar                                                       1
anand garden, sector-105                                       1
sector-7 hous                                                  1
near euro                                                      1
shankar vihar                                                  1
godrej aria , sector 79 ,                                      1
gopal nagar, garhi ghasita, sonipat                            1
south city                                                     1
shivji park colony                                             1
near pataudi chowk                                             1
heritage city                                                  1
jat colony,fazilpur/taj nagar road                             1
saroop garden rajendra park                                    1
near khandsa road                                              1
Name: count, dtype: int64

In [67]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [68]:
df.sector.value_counts()

sector
sohna road                                                   154
sector 85                                                    108
sector 102                                                   107
sector 92                                                     99
sector 69                                                     93
sector 90                                                     88
sector 81                                                     87
sector 65                                                     87
sector 109                                                    86
sector 79                                                     76
sector 104                                                    69
sector 83                                                     68
sector 86                                                     64
sector 37d                                                    63
sector 50                                                     63
sector 107                                                    60
sector 108                                                    58
sector 56                                                     56
sector 48                                                     55
sector 2                                                      54
sector 95                                                     54
sector 70a                                                    54
sector 37c                                                    51
sector 43                                                     51
sector 26                                                     50
sector-33 sohna road                                          50
sector 70                                                     50
sector 84                                                     49
sector 89                                                     49
sector 49                                                     48
sector 67                                                     47
sector 113                                                    43
sector 61                                                     42
sector 66                                                     42
sector 103                                                    42
sector 82                                                     41
sector 25                                                     40
sector 7                                                      39
sector 106                                                    38
sector 28                                                     38
sector 4                                                      35
sector 68                                                     30
sector 54                                                     30
sector 99a                                                    30
sector 12                                                     29
sector 72                                                     29
sector 77                                                     27
sector 71                                                     27
sector 57                                                     24
sector 112                                                    23
sector 111                                                    22
sector 24                                                     22
sector 88a                                                    22
sector 67a                                                    21
sector 3                                                      20
sector 22                                                     20
sector 33                                                     19
sector 82a                                                    19
sector 14                                                     19
sector 105                                                    19
sector 74                                                     18
sector 47                                                     18
sector 78                                                     17
sector 91                                                     17
sector 62                                                     16
sector 63a                                                    15
sector 60                                                     15
sector 11                                                     15
sector 110                                                    15
gwal pahari                                                   14
sector 53                                                     14
sector 1 manesar                                              14
sector 52                                                     14
sector 76                                                     14
sector 63                                                     14
sector 6                                                      13
sector 4 phase 2                                              13
sector 55                                                     13
sector 46                                                     13
sector 31                                                     12
sohna road road                                               12
sector 36a                                                    12
sector 38                                                     12
sector 99                                                     12
sector 41                                                     11
sector 3 phase 3 extension                                    11
sector 39                                                     11
sector 9a                                                     10
sector 1a manesar                                             10
sector 13                                                     10
manesar                                                        9
sector 93                                                      9
c block sector 43                                              8
sector 23                                                      8
sector 45                                                      8
sector 2 extension                                             8
sector 40                                                      8
sector 89 a                                                    8
dwarka expressway                                              8
sector 59                                                      8
sector 95a                                                     8
sector 17                                                      8
sector 3 phase 2                                               8
sector 36 sohna road                                           7
sector 10a                                                     7
sector 58                                                      7
sector 51                                                      7
sector 1                                                       6
sector 5                                                       6
sector 30                                                      5
new sector 2                                                   5
arjun nagar                                                    5
saraswati vihar                                                5
sector 80                                                      5
sector 9                                                       5
sector 23a                                                     5
sector 12a                                                     4
sector 3a                                                      4
new                                                            4
surya vihar                                                    4
valley view estate                                             4
devilal colony                                                 4
sector 36                                                      4
vishnu garden                                                  4
ravi nagar                                                     4
bhondsi                                                        4
sector 17a                                                     3
a block sector 43                                              3
sector 8                                                       3
sector 27                                                      3
b block sector 43                                              3
sector 15                                                      3
patel nagar                                                    3
maruti kunj                                                    3
sector 88b                                                     3
sector 17b                                                     3
sector 110 a                                                   3
sector 73                                                      3
new sector 2 phase 2                                           2
golf course road                                               2
nars                                                           2
west sector 13                                                 2
hira nagar                                                     2
surat nagar                                                    2
golf course ext road                                           2
rosewood                                                       2
sector 21                                                      2
sector 15 part 2                                               2
faridabad road                                                 2
block a surya vihar                                            2
rajiv chowk                                                    2
ambience island                                                2
sheetla colony                                                 2
farukhnagar                                                    2
mohan nagar                                                    2
surat nagar phase 2                                            2
manohar nagar                                                  2
acharya puri                                                   2
sector-2 sohna road                                            2
mayfield garden                                                2
, delhi ncr                                                    2
shanti nagar                                                   2
sector-11 sohna road                                           2
lajpat nagar                                                   2
iffco chowk                                                    2
bissar                                                         2
sector 15 part 1                                               2
bhawani enclave                                                2
sector 32                                                      2
new basti                                                      2
sushant lok                                                    2
new sector 2 phase 1                                           2
pratap nagar                                                   2
daulatabad                                                     2
sohna road  road                                               2
mahasector 11, rajendra place                                  1
begampur khatola                                               1
hsiidc plot sector 1 manesar                                   1
sector 50 pocket h                                             1
ansal's sector 2                                               1
v block sector 24                                              1
near sector 1 market                                           1
sector 5 chowk                                                 1
old delhi road, opp sector-14                                  1
near nand hospital                                             1
bptp                                                           1
sultanpur                                                      1
laxmna vihar, phase 2                                          1
sector 7, sector 7                                             1
kanahi                                                         1
huda saraswati vihar                                           1
tekchand nagar                                                 1
new sector 7                                                   1
sector 21a faridabad                                           1
garauli kalan                                                  1
damdma                                                         1
sec 3 bhim vihar part 1 bhimgher kheri                         1
sector-35 sohna road                                           1
part 3 sector 5                                                1
sector 3 phase 3                                               1
park view                                                      1
rajiv colony                                                   1
urban estate, sector 5                                         1
sector 37a                                                     1
ravi nager basai road                                          1
civil l                                                        1
ram nagar                                                      1
sector-5 sheetla colony                                        1
g block dlf city phase 1                                       1
saraswati enclave                                              1
lucknow                                                        1
sector 4, railway road,                                        1
bhimgarh kheri phase 3                                         1
dhankot                                                        1
b1 block sector 57                                             1
saroop garden sector 105                                       1
sector-5 sohna road                                            1
bhora kalan                                                    1
sispal vihar                                                   1
block g sector-57                                              1
devi lal colony gali no 12 gurgaon nr omkar public school      1
cyber city                                                     1
mahavir pura                                                   1
samaspur                                                       1
block h sector 3 phase iii extension                           1
ats marigold                                                   1
sector 12 near sadar bazar                                     1
rattan garden                                                  1
hno 13 sagar enclave sura                                      1
sector 3 phase i                                               1
sector 37b                                                     1
vir nagar                                                      1
sector 42                                                      1
pataudi road                                                   1
anand garden, sector-105                                       1
kheri                                                          1
alipur                                                         1
sector 9b                                                      1
sai kunj                                                       1
sadar bazar                                                    1
khandsa                                                        1
sector 17c                                                     1
carterpuri village                                             1
om nagar                                                       1
sector-7 hous                                                  1
jat colony,fazilpur/taj nagar road                             1
near euro                                                      1
shankar vihar                                                  1
godrej aria , sector 79 ,                                      1
gopal nagar, garhi ghasita, sonipat                            1
south city                                                     1
shivji park colony                                             1
near pataudi chowk                                             1
heritage city                                                  1
sector 4 urban estate                                          1
near khandsa road                                              1
Name: count, dtype: int64

In [69]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [70]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [71]:
df.sector.value_counts()

sector
sohna road                    154
sector 85                     108
sector 102                    107
sector 92                      99
sector 69                      93
sector 90                      88
sector 65                      87
sector 81                      87
sector 109                     86
sector 79                      76
sector 104                     69
sector 33                      69
sector 83                      68
sector 43                      65
sector 86                      64
sector 37d                     63
sector 50                      63
sector 95                      62
sector 2                       62
sector 107                     60
sector 108                     58
sector 89                      57
sector 56                      56
sector 48                      55
sector 70a                     54
sector 37c                     51
sector 26                      50
sector 70                      50
sector 84                      49
sector 49                      48
sector 4                       48
sector 67                      47
sector 113                     43
sector 61                      42
sector 103                     42
sector 66                      42
sector 82                      41
sector 25                      40
sector 7                       39
sector 28                      38
sector 106                     38
sector 12                      36
manesar                        33
sector 54                      30
sector 99a                     30
sector 68                      30
sector 72                      29
sector 77                      27
sector 71                      27
sector 3                       24
sector 57                      24
sector 112                     23
sector 111                     22
sector 24                      22
sector 88a                     22
sector 67a                     21
sector 22                      20
sector 14                      19
sector 82a                     19
sector 105                     19
sector 74                      18
sector 47                      18
sector 110                     18
sector 91                      17
sector 78                      17
sector 62                      16
sector 63a                     15
sector 60                      15
sector 11                      15
sector 53                      14
sector 52                      14
gwal pahari                    14
sector 76                      14
sector 63                      14
sector 23                      13
sector 6                       13
sector 46                      13
sector 55                      13
sohna road road                12
sector 36a                     12
sector 31                      12
sector 38                      12
sector 99                      12
sector 36                      11
sector 3 phase 3 extension     11
sector 41                      11
sector 39                      11
sector 9a                      10
sector 13                      10
sector 93                       9
sector 3 phase 2                8
sector 45                       8
sector 17                       8
sector 40                       8
dwarka expressway               8
sector 59                       8
sector 58                       7
sector 51                       7
sector 10a                      7
sector 5                        6
sector 1                        6
sector 15                       6
sector 30                       5
saraswati vihar                 5
new sector 2                    5
arjun nagar                     5
sector 9                        5
sector 80                       5
devilal colony                  4
new                             4
surya vihar                     4
bhondsi                         4
ravi nagar                      4
vishnu garden                   4
valley view estate              4
sector 8                        3
sector 17b                      3
sector 73                       3
sector 27                       3
sector 17a                      3
sector 88b                      3
Name: count, dtype: int64

In [72]:
df[df['sector'] == 'new']

,property_name,type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
370,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,NaN,"New Gurgaon, Gurgaon, Haryana",3.0,DK,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN
2093,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,NaN,"New Gurgaon, Gurgaon, Haryana",7.0,DK,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ..."
2867,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,NaN,"New Gurgaon, Gurgaon, Haryana",3.0,DK,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'..."
3009,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"Study Room,Servant Room","New Gurgaon, Gurgaon, Haryana",4.0,DK,Jun-27,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."

In [73]:
df.loc[2867,'sector'] = 'sector 37'
df.loc[370,'sector'] = 'sector 92'
df.loc[2093,'sector'] = 'sector 90'
df.loc[3009,'sector'] = 'sector 76'

In [74]:
df[df['sector'] == 'new sector 2']

,property_name,type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features
493,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,NaN,"New Palam Vihar, Gurgaon, Haryana",1.0,DK,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN
1283,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,NaN,"New Palam Vihar, Gurgaon, Haryana",1.0,DK,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN
1630,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,269.0,Plot area 270(25.08 sq.m.),2,2,2,NaN,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']"
2369,3 Bedroom House for sale in New Palam Vihar,house,NaN,new sector 2,1.00,8796.0,1076.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,Pooja Room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN
3457,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,Others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,DK,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']"

In [75]:
df.loc[[493,1283,1630,2369,3457],'sector'] = 'sector 110'

In [76]:
df.duplicated().sum()

0

In [77]:
df.shape

(3662, 20)

In [78]:
df.sector.value_counts()

sector
sohna road                    154
sector 85                     108
sector 102                    107
sector 92                     100
sector 69                      93
sector 90                      89
sector 65                      87
sector 81                      87
sector 109                     86
sector 79                      76
sector 104                     69
sector 33                      69
sector 83                      68
sector 43                      65
sector 86                      64
sector 37d                     63
sector 50                      63
sector 95                      62
sector 2                       62
sector 107                     60
sector 108                     58
sector 89                      57
sector 56                      56
sector 48                      55
sector 70a                     54
sector 37c                     51
sector 26                      50
sector 70                      50
sector 84                      49
sector 49                      48
sector 4                       48
sector 67                      47
sector 113                     43
sector 61                      42
sector 103                     42
sector 66                      42
sector 82                      41
sector 25                      40
sector 7                       39
sector 28                      38
sector 106                     38
sector 12                      36
manesar                        33
sector 54                      30
sector 99a                     30
sector 68                      30
sector 72                      29
sector 77                      27
sector 71                      27
sector 3                       24
sector 57                      24
sector 112                     23
sector 110                     23
sector 111                     22
sector 24                      22
sector 88a                     22
sector 67a                     21
sector 22                      20
sector 14                      19
sector 82a                     19
sector 105                     19
sector 74                      18
sector 47                      18
sector 91                      17
sector 78                      17
sector 62                      16
sector 63a                     15
sector 60                      15
sector 76                      15
sector 11                      15
sector 53                      14
sector 52                      14
gwal pahari                    14
sector 63                      14
sector 23                      13
sector 6                       13
sector 46                      13
sector 55                      13
sector 31                      12
sohna road road                12
sector 36a                     12
sector 99                      12
sector 38                      12
sector 36                      11
sector 3 phase 3 extension     11
sector 41                      11
sector 39                      11
sector 9a                      10
sector 13                      10
sector 93                       9
sector 17                       8
sector 3 phase 2                8
sector 59                       8
dwarka expressway               8
sector 45                       8
sector 40                       8
sector 51                       7
sector 10a                      7
sector 58                       7
sector 5                        6
sector 15                       6
sector 1                        6
sector 30                       5
saraswati vihar                 5
arjun nagar                     5
sector 80                       5
sector 9                        5
devilal colony                  4
bhondsi                         4
ravi nagar                      4
vishnu garden                   4
surya vihar                     4
valley view estate              4
sector 73                       3
sector 27                       3
sector 17a                      3
sector 8                        3
sector 17b                      3
sector 88b                      3
sector 37                       1
Name: count, dtype: int64

In [79]:
df.to_csv('data_gurgaon_properties_cleaned_v1.csv',index=False)